const c=(id,en,hi,description="")=>({id,title:`${en} / ${hi}`,description});
const g=(id,en,hi,concepts=[],description="")=>({id,title:`${en} / ${hi}`,concepts,description});
const nodes=(subjectId,en,hi,groups)=>{
 const subjectNodeId=`neet.ug.${subjectId}`;
 const subject={exam:"neet",nodeId:subjectNodeId,parentId:"",level:"subject",title:`${en} / ${hi}`,description:"Official NEET (UG)-2026 syllabus"};
 const out=[subject];
 for(const group of groups){
  const topicId=`${subjectNodeId}.${group.id}`;
  out.push({exam:"neet",nodeId:topicId,parentId:subjectNodeId,level:"topic",title:group.title,description:group.description||""});
  for(const concept of group.concepts||[]) out.push({exam:"neet",nodeId:`${topicId}.${concept.id}`,parentId:topicId,level:"concept",title:concept.title,description:concept.description||""});
 }
 return out;
};

export const NEET_SYLLABUS=[
 ...nodes("physics","Physics","भौतिकी",[
  g("unit_01","Unit 1: Physics and Measurement","इकाई 1: भौतिकी एवं मापन",[c("measurements","Units, SI units, least count, significant figures, errors and dimensions","इकाइयाँ, SI इकाइयाँ, अल्पतमांक, सार्थक अंक, त्रुटियाँ एवं विमाएँ")]),
  g("unit_02","Unit 2: Kinematics","इकाई 2: गतिकी",[c("kinematics","Frame of reference, straight-line motion, vectors, relative velocity, projectile and circular motion","संदर्भ-तंत्र, सरल रेखीय गति, सदिश, सापेक्ष वेग, प्रक्षेप्य एवं वृत्तीय गति")]),
  g("unit_03","Unit 3: Laws of Motion","इकाई 3: गति के नियम",[c("laws_motion","Newton's laws, momentum, impulse, conservation of momentum, equilibrium and friction","न्यूटन के नियम, संवेग, आवेग, संवेग संरक्षण, साम्यावस्था एवं घर्षण")]),
  g("unit_04","Unit 4: Work, Energy and Power","इकाई 4: कार्य, ऊर्जा एवं शक्ति",[c("work_energy","Work by constant and variable force, kinetic and potential energy, work-energy theorem, power, collisions","स्थिर एवं परिवर्ती बल का कार्य, गतिज एवं स्थितिज ऊर्जा, कार्य-ऊर्जा प्रमेय, शक्ति एवं टक्कर")]),
  g("unit_05","Unit 5: Rotational Motion","इकाई 5: घूर्णन गति",[c("rotation","Centre of mass, torque, angular momentum, moment of inertia, rigid-body equilibrium and rotation","द्रव्यमान केंद्र, बल आघूर्ण, कोणीय संवेग, जड़त्व आघूर्ण, दृढ़ पिंड साम्य एवं घूर्णन")]),
  g("unit_06","Unit 6: Gravitation","इकाई 6: गुरुत्वाकर्षण",[c("gravitation","Universal gravitation, variation of g, Kepler laws, gravitational potential, escape velocity and satellites","सार्वत्रिक गुरुत्वाकर्षण, g में परिवर्तन, केप्लर नियम, गुरुत्वीय विभव, पलायन वेग एवं उपग्रह")]),
  g("unit_07","Unit 7: Properties of Solids and Liquids","इकाई 7: ठोस एवं द्रवों के गुण",[c("matter_properties","Elasticity, fluids, viscosity, Bernoulli principle, surface tension, heat and thermal properties","प्रत्यास्थता, द्रव, श्यानता, बर्नौली सिद्धांत, पृष्ठ तनाव, ऊष्मा एवं तापीय गुण")]),
  g("unit_08","Unit 8: Thermodynamics","इकाई 8: ऊष्मागतिकी",[c("thermodynamics","Thermal equilibrium, zeroth law, heat, work, internal energy, first and second laws","तापीय साम्य, शून्यवाँ नियम, ऊष्मा, कार्य, आंतरिक ऊर्जा तथा प्रथम एवं द्वितीय नियम")]),
  g("unit_09","Unit 9: Kinetic Theory of Gases","इकाई 9: गैसों का गतिज सिद्धांत",[c("kinetic_gas","Perfect gas equation, kinetic interpretation, RMS speed, degrees of freedom, equipartition and Avogadro number","आदर्श गैस समीकरण, गतिज व्याख्या, RMS वेग, स्वतंत्रता की कोटियाँ, समविभाजन एवं एवोगैड्रो संख्या")]),
  g("unit_10","Unit 10: Oscillations and Waves","इकाई 10: दोलन एवं तरंगें",[c("oscillations_waves","Periodic motion, SHM, energy in SHM, wave motion, superposition, standing waves and beats","आवर्ती गति, सरल आवर्त गति, SHM की ऊर्जा, तरंग गति, अध्यारोपण, स्थिर तरंगें एवं बीट्स")]),
  g("unit_11","Unit 11: Electrostatics","इकाई 11: स्थिरवैद्युतिकी",[c("electrostatics","Charge, Coulomb law, electric field, dipole, Gauss law, potential, conductors, dielectrics and capacitors","आवेश, कूलॉम नियम, वैद्युत क्षेत्र, द्विध्रुव, गाउस नियम, विभव, चालक, परावैद्युत एवं संधारित्र")]),
  g("unit_12","Unit 12: Current Electricity","इकाई 12: धारा विद्युत",[c("current_electricity","Drift velocity, Ohm law, resistance, energy and power, cells, Kirchhoff laws and bridge circuits","अपवाह वेग, ओम नियम, प्रतिरोध, ऊर्जा एवं शक्ति, सेल, किर्चॉफ नियम एवं ब्रिज परिपथ")]),
  g("unit_13","Unit 13: Magnetic Effects of Current and Magnetism","इकाई 13: धारा के चुंबकीय प्रभाव एवं चुंबकत्व",[c("magnetism","Biot-Savart law, Ampere law, magnetic force, galvanometer, magnetic dipole and magnetic materials","बायो-सावर्ट नियम, एम्पियर नियम, चुंबकीय बल, गैल्वेनोमीटर, चुंबकीय द्विध्रुव एवं चुंबकीय पदार्थ")]),
  g("unit_14","Unit 14: Electromagnetic Induction and Alternating Currents","इकाई 14: वैद्युतचुंबकीय प्रेरण एवं प्रत्यावर्ती धाराएँ",[c("emi_ac","Faraday and Lenz laws, inductance, AC, LCR circuit, resonance, AC power, generator and transformer","फैराडे एवं लेंज नियम, प्रेरकत्व, AC, LCR परिपथ, अनुनाद, AC शक्ति, जनित्र एवं ट्रांसफॉर्मर")]),
  g("unit_15","Unit 15: Electromagnetic Waves","इकाई 15: वैद्युतचुंबकीय तरंगें",[c("em_waves","Displacement current, electromagnetic waves, spectrum and applications","विस्थापन धारा, वैद्युतचुंबकीय तरंगें, स्पेक्ट्रम एवं अनुप्रयोग")]),
  g("unit_16","Unit 16: Optics","इकाई 16: प्रकाशिकी",[c("optics","Reflection, mirrors, refraction, lenses, optical instruments, interference, diffraction and polarisation","परावर्तन, दर्पण, अपवर्तन, लेंस, प्रकाशीय यंत्र, व्यतिकरण, विवर्तन एवं ध्रुवण")]),
  g("unit_17","Unit 17: Dual Nature of Matter and Radiation","इकाई 17: पदार्थ एवं विकिरण की द्वैत प्रकृति",[c("dual_nature","Photoelectric effect, Einstein equation, matter waves and de Broglie relation","प्रकाशवैद्युत प्रभाव, आइंस्टीन समीकरण, पदार्थ तरंगें एवं डी-ब्रॉग्ली संबंध")]),
  g("unit_18","Unit 18: Atoms and Nuclei","इकाई 18: परमाणु एवं नाभिक",[c("atoms_nuclei","Rutherford and Bohr models, spectra, nuclear composition, mass defect, binding energy, fission and fusion","रदरफोर्ड एवं बोहर मॉडल, स्पेक्ट्रा, नाभिकीय संरचना, द्रव्यमान क्षति, बंधन ऊर्जा, विखंडन एवं संलयन")]),
  g("unit_19","Unit 19: Electronic Devices","इकाई 19: इलेक्ट्रॉनिक युक्तियाँ",[c("electronics","Semiconductors, p-n junction, diode, LED, photodiode, solar cell, Zener diode and logic gates","अर्धचालक, p-n जंक्शन, डायोड, LED, फोटोडायोड, सौर सेल, जेनर डायोड एवं लॉजिक गेट")]),
  g("unit_20","Unit 20: Experimental Skills","इकाई 20: प्रायोगिक कौशल",[c("experimental_skills","Vernier calipers, screw gauge, pendulum, metre scale, elasticity, surface tension, viscosity, sound, heat, resistance, galvanometer, optics and semiconductor experiments","वर्नियर कैलिपर्स, स्क्रू गेज, लोलक, मीटर स्केल, प्रत्यास्थता, पृष्ठ तनाव, श्यानता, ध्वनि, ऊष्मा, प्रतिरोध, गैल्वेनोमीटर, प्रकाशिकी एवं अर्धचालक प्रयोग")])
 ]),
 ...nodes("chemistry","Chemistry","रसायन विज्ञान",[
  g("unit_01","Unit 1: Some Basic Concepts in Chemistry","इकाई 1: रसायन विज्ञान की मूल अवधारणाएँ",[c("basic_concepts","Matter, atomic theory, atoms, molecules, mole concept, molar mass, composition and stoichiometry","पदार्थ, परमाणु सिद्धांत, परमाणु, अणु, मोल अवधारणा, मोलर द्रव्यमान, संघटन एवं स्टॉइकियोमेट्री")]),
  g("unit_02","Unit 2: Atomic Structure","इकाई 2: परमाणु संरचना",[c("atomic_structure","Radiation, photoelectric effect, hydrogen spectrum, Bohr model, quantum mechanics, orbitals, quantum numbers and electronic configuration","विकिरण, प्रकाशवैद्युत प्रभाव, हाइड्रोजन स्पेक्ट्रम, बोहर मॉडल, क्वांटम यांत्रिकी, कक्षक, क्वांटम संख्याएँ एवं इलेक्ट्रॉनिक विन्यास")]),
  g("unit_03","Unit 3: Chemical Bonding and Molecular Structure","इकाई 3: रासायनिक आबंधन एवं आणविक संरचना",[c("bonding","Ionic and covalent bonds, electronegativity, VSEPR, hybridisation, valence bond theory, molecular orbital theory and hydrogen bonding","आयनिक एवं सहसंयोजक बंध, विद्युतऋणात्मकता, VSEPR, संकरण, संयोजकता बंध सिद्धांत, आणविक कक्षक सिद्धांत एवं हाइड्रोजन बंध")]),
  g("unit_04","Unit 4: Chemical Thermodynamics","इकाई 4: रासायनिक ऊष्मागतिकी",[c("chemical_thermo","System and surroundings, enthalpy, heat capacity, Hess law, entropy, spontaneity and Gibbs energy","तंत्र एवं परिवेश, एन्थैल्पी, ऊष्मा धारिता, हेस नियम, एंट्रॉपी, स्वतःस्फूर्तता एवं गिब्स ऊर्जा")]),
  g("unit_05","Unit 5: Solutions","इकाई 5: विलयन",[c("solutions","Molarity, molality, mole fraction, vapour pressure, Raoult law, colligative properties and van't Hoff factor","मोलरता, मोललता, मोल अंश, वाष्प दाब, राउल्ट नियम, अणुसंख्य गुणधर्म एवं वान्ट हॉफ गुणक")]),
  g("unit_06","Unit 6: Equilibrium","इकाई 6: साम्यावस्था",[c("equilibrium","Physical and chemical equilibrium, equilibrium constants, Le Chatelier principle, ionic equilibrium, pH, buffers and solubility equilibria","भौतिक एवं रासायनिक साम्य, साम्य स्थिरांक, ले-शातेलिए सिद्धांत, आयनिक साम्य, pH, बफर एवं विलेयता साम्य")]),
  g("unit_07","Unit 7: Redox Reactions and Electrochemistry","इकाई 7: रेडॉक्स अभिक्रियाएँ एवं वैद्युत रसायन",[c("electrochemistry","Oxidation-reduction, oxidation number, electrolysis, conductivity, cells, electrode potential, Nernst equation, batteries and fuel cells","ऑक्सीकरण-अपचयन, ऑक्सीकरण संख्या, विद्युत अपघटन, चालकता, सेल, इलेक्ट्रोड विभव, नर्न्स्ट समीकरण, बैटरी एवं ईंधन सेल")]),
  g("unit_08","Unit 8: Chemical Kinetics","इकाई 8: रासायनिक बलगतिकी",[c("kinetics","Rate of reaction, factors, order, molecularity, rate law, half-life, Arrhenius theory and activation energy","अभिक्रिया वेग, कारक, कोटि, आणविकता, वेग नियम, अर्ध-आयु, आर्हेनियस सिद्धांत एवं सक्रियण ऊर्जा")]),
  g("unit_09","Unit 9: Classification of Elements and Periodicity in Properties","इकाई 9: तत्वों का वर्गीकरण एवं गुणों में आवर्तिता",[c("periodicity","Modern periodic law, periodic table, s-p-d-f blocks, atomic and ionic radii, ionisation enthalpy, electron gain enthalpy, valence and oxidation states","आधुनिक आवर्त नियम, आवर्त सारणी, s-p-d-f ब्लॉक, परमाणु एवं आयनिक त्रिज्या, आयनीकरण एन्थैल्पी, इलेक्ट्रॉन ग्रहण एन्थैल्पी, संयोजकता एवं ऑक्सीकरण अवस्थाएँ")]),
  g("unit_10","Unit 10: P-Block Elements","इकाई 10: p-ब्लॉक तत्व",[c("p_block","Groups 13 to 18, electronic configuration and general trends in physical and chemical properties","समूह 13 से 18, इलेक्ट्रॉनिक विन्यास तथा भौतिक एवं रासायनिक गुणों की सामान्य प्रवृत्तियाँ")]),
  g("unit_11","Unit 11: d- and f-Block Elements","इकाई 11: d- एवं f-ब्लॉक तत्व",[c("df_block","Transition elements, electronic configuration, properties, oxidation states, complexes, alloys, lanthanoids and actinoids","संक्रमण तत्व, इलेक्ट्रॉनिक विन्यास, गुण, ऑक्सीकरण अवस्थाएँ, संकुल, मिश्रधातु, लैंथेनॉइड एवं ऐक्टिनॉइड")]),
  g("unit_12","Unit 12: Coordination Compounds","इकाई 12: उपसहसंयोजन यौगिक",[c("coordination","Werner theory, ligands, coordination number, nomenclature, isomerism, bonding, colour, magnetic properties and applications","वर्नर सिद्धांत, लिगैंड, उपसहसंयोजन संख्या, नामकरण, समावयवता, आबंधन, रंग, चुंबकीय गुण एवं अनुप्रयोग")]),
  g("unit_13","Unit 13: Purification and Characterisation of Organic Compounds","इकाई 13: कार्बनिक यौगिकों का शुद्धिकरण एवं अभिलक्षणन",[c("organic_analysis","Crystallisation, sublimation, distillation, chromatography, qualitative and quantitative analysis","क्रिस्टलीकरण, ऊर्ध्वपातन, आसवन, क्रोमैटोग्राफी, गुणात्मक एवं मात्रात्मक विश्लेषण")]),
  g("unit_14","Unit 14: Some Basic Principles of Organic Chemistry","इकाई 14: कार्बनिक रसायन की मूल अवधारणाएँ",[c("organic_basics","Tetravalency, hybridisation, classification, isomerism, nomenclature, reaction intermediates, electronic effects and reaction types","चतुसंयोजकता, संकरण, वर्गीकरण, समावयवता, नामकरण, अभिक्रिया मध्यवर्ती, इलेक्ट्रॉनिक प्रभाव एवं अभिक्रिया प्रकार")]),
  g("unit_15","Unit 15: Hydrocarbons","इकाई 15: हाइड्रोकार्बन",[c("hydrocarbons","Alkanes, alkenes, alkynes and aromatic hydrocarbons: nomenclature, preparation, properties and reactions","एल्केन, एल्कीन, एल्काइन एवं एरोमैटिक हाइड्रोकार्बन: नामकरण, निर्माण, गुण एवं अभिक्रियाएँ")]),
  g("unit_16","Unit 16: Organic Compounds Containing Halogens","इकाई 16: हैलोजन युक्त कार्बनिक यौगिक",[c("halo_compounds","Preparation, properties, reactions, C-X bond, substitution mechanisms and environmental effects","निर्माण, गुण, अभिक्रियाएँ, C-X बंध, प्रतिस्थापन तंत्र एवं पर्यावरणीय प्रभाव")]),
  g("unit_17","Unit 17: Organic Compounds Containing Oxygen","इकाई 17: ऑक्सीजन युक्त कार्बनिक यौगिक",[c("oxygen_compounds","Alcohols, phenols, ethers, aldehydes, ketones and carboxylic acids: preparation, properties, reactions and uses","अल्कोहल, फीनॉल, ईथर, ऐल्डिहाइड, कीटोन एवं कार्बोक्सिलिक अम्ल: निर्माण, गुण, अभिक्रियाएँ एवं उपयोग")]),
  g("unit_18","Unit 18: Organic Compounds Containing Nitrogen","इकाई 18: नाइट्रोजन युक्त कार्बनिक यौगिक",[c("nitrogen_compounds","Amines, nomenclature, classification, basic character, preparation, reactions and diazonium salts","अमीन, नामकरण, वर्गीकरण, क्षारीय प्रकृति, निर्माण, अभिक्रियाएँ एवं डायजोनीयम लवण")]),
  g("unit_19","Unit 19: Biomolecules","इकाई 19: जैव-अणु",[c("biomolecules","Carbohydrates, proteins, vitamins, nucleic acids and hormones","कार्बोहाइड्रेट, प्रोटीन, विटामिन, न्यूक्लिक अम्ल एवं हार्मोन")]),
  g("unit_20","Unit 20: Principles Related to Practical Chemistry","इकाई 20: प्रायोगिक रसायन के सिद्धांत",[c("practical_chemistry","Detection of elements and functional groups, preparation of compounds, titrimetric exercises, qualitative salt analysis and selected experiments","तत्व एवं क्रियात्मक समूहों की पहचान, यौगिक निर्माण, टाइट्रीमेट्रिक अभ्यास, गुणात्मक लवण विश्लेषण एवं चयनित प्रयोग")])
 ]),
 ...nodes("biology","Biology","जीवविज्ञान",[
  g("unit_01","Unit 1: Diversity in Living World","इकाई 1: जीव जगत में विविधता",[c("diversity","What is living, biodiversity, taxonomy, five kingdoms, plants and animals classification, lichens, viruses and viroids","जीवन की अवधारणा, जैवविविधता, वर्गिकी, पंच-जगत, पादप एवं जन्तु वर्गीकरण, लाइकेन, विषाणु एवं वाइरॉइड")]),
  g("unit_02","Unit 2: Structural Organisation in Animals and Plants","इकाई 2: जन्तुओं एवं पादपों में संरचनात्मक संगठन",[c("structure","Morphology and anatomy of flowering plants, plant families, animal tissues and major systems of insect and frog","पुष्पीय पादपों की आकारिकी एवं शारीरिकी, पादप कुल, जन्तु ऊतक तथा कीट एवं मेंढक की प्रमुख तंत्र-रचनाएँ")]),
  g("unit_03","Unit 3: Cell Structure and Function","इकाई 3: कोशिका संरचना एवं कार्य",[c("cell","Cell theory, prokaryotic/eukaryotic cells, organelles, biomolecules, enzymes and cell division","कोशिका सिद्धांत, प्रोकैरियोटिक/यूकैरियोटिक कोशिका, कोशिकांग, जैव-अणु, एंजाइम एवं कोशिका विभाजन")]),
  g("unit_04","Unit 4: Plant Physiology","इकाई 4: पादप शरीर क्रिया विज्ञान",[c("plant_physiology","Photosynthesis, respiration, plant growth and development, growth regulators and C3/C4 pathways","प्रकाश संश्लेषण, श्वसन, पादप वृद्धि एवं विकास, वृद्धि नियामक तथा C3/C4 मार्ग")]),
  g("unit_05","Unit 5: Human Physiology","इकाई 5: मानव शरीर क्रिया विज्ञान",[c("human_physiology","Breathing, circulation, excretion, locomotion, neural control and chemical coordination; related disorders","श्वसन, परिसंचरण, उत्सर्जन, गमन, तंत्रिका नियंत्रण एवं रासायनिक समन्वय तथा संबंधित विकार")]),
  g("unit_06","Unit 6: Reproduction","इकाई 6: प्रजनन",[c("reproduction","Sexual reproduction in flowering plants, human reproduction, reproductive health, contraception, MTP and assisted reproductive technologies","पुष्पीय पादपों में लैंगिक प्रजनन, मानव प्रजनन, प्रजनन स्वास्थ्य, गर्भनिरोध, MTP एवं सहायक प्रजनन तकनीकें")]),
  g("unit_07","Unit 7: Genetics and Evolution","इकाई 7: आनुवंशिकी एवं विकास",[c("genetics_evolution","Mendelian inheritance, chromosomal theory, linkage, crossing over, molecular basis of inheritance, DNA/RNA, gene expression and evolution","मेंडलियन वंशागति, गुणसूत्र सिद्धांत, linkage, crossing over, वंशागति का आणविक आधार, DNA/RNA, जीन अभिव्यक्ति एवं विकास")]),
  g("unit_08","Unit 8: Biology and Human Welfare","इकाई 8: जीवविज्ञान एवं मानव कल्याण",[c("human_welfare","Health and disease, pathogens, immunity, cancer, HIV/AIDS, drug and alcohol abuse and microbes in human welfare","स्वास्थ्य एवं रोग, रोगजनक, प्रतिरक्षा, कैंसर, HIV/AIDS, मादक द्रव्य एवं अल्कोहल दुरुपयोग तथा मानव कल्याण में सूक्ष्मजीव")]),
  g("unit_09","Unit 9: Biotechnology and Its Applications","इकाई 9: जैव प्रौद्योगिकी एवं उसके अनुप्रयोग",[c("biotechnology","Recombinant DNA technology, genetic engineering, insulin and vaccines, gene therapy, Bt crops, transgenic animals and biosafety","पुनर्संयोजक DNA तकनीक, आनुवंशिक अभियांत्रिकी, इंसुलिन एवं टीके, जीन थेरेपी, Bt फसलें, ट्रांसजेनिक जन्तु एवं जैवसुरक्षा")]),
  g("unit_10","Unit 10: Ecology and Environment","इकाई 10: पारिस्थितिकी एवं पर्यावरण",[c("ecology","Organisms and environment, population interactions, ecosystem, energy flow, pyramids, biodiversity and conservation","जीव एवं पर्यावरण, जनसंख्या अंतःक्रियाएँ, पारितंत्र, ऊर्जा प्रवाह, पारिस्थितिक पिरामिड, जैवविविधता एवं संरक्षण")])
 ])
];

export const NEET_SYLLABUS_VERSION="NEET (UG)-2026 / NMC syllabus notified 22-12-2025";
