import {createClient} from "@supabase/supabase-js";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
export const cloudEnabled=Boolean(url&&key);
export const supabase=cloudEnabled?createClient(url,key):null;
export function cloudUserEmail(userId){return `${String(userId).trim().toLowerCase().replace(/[^a-z0-9._-]/g,"-")}@adaptive-syllabus.local`;}
const PROFILE_FIELDS="id,user_id,name,dob,exam,role,created_at";
export async function cloudSignUp({userId,password,name,dob,exams}){if(!supabase)throw new Error("Cloud mode is not configured");const selected=Array.isArray(exams)&&exams.length?exams:["ras"];const {data,error}=await supabase.auth.signUp({email:cloudUserEmail(userId),password,options:{data:{user_id:userId,name,dob,exam:selected[0]}}});if(error)throw error;return data;}
export async function cloudSignIn(userId,password){if(!supabase)throw new Error("Cloud mode is not configured");const {data,error}=await supabase.auth.signInWithPassword({email:cloudUserEmail(userId),password});if(error)throw error;return data;}
export async function cloudSignOut(){if(supabase)await supabase.auth.signOut();}
export async function getCloudProfile(){if(!supabase)return null;const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data,error}=await supabase.from("profiles").select(PROFILE_FIELDS).eq("id",user.id).single();if(error)throw error;return data;}
export async function getCloudProfiles(){if(!supabase)return[];const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in first.");const {data,error}=await supabase.from("profiles").select(PROFILE_FIELDS).order("created_at",{ascending:true});if(error)throw error;return data||[];}
export async function getCloudAdminAttempts(){if(!supabase)return[];const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in first.");const {data,error}=await supabase.from("attempts").select("id,user_id,exam,question_id,node_id,selected,answer,correct,created_at").order("created_at",{ascending:false});if(error)throw error;return data||[];}
export async function updateCloudUserRole(id,role){if(!supabase)throw new Error("Cloud mode is not configured");const allowed=["student","mentor","admin"];if(!allowed.includes(role))throw new Error("Invalid role.");const {data,error}=await supabase.from("profiles").update({role}).eq("id",id).select(PROFILE_FIELDS).single();if(error)throw error;return data;}
export async function deleteCloudUser(id){if(!supabase)throw new Error("Cloud mode is not configured");const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Please sign in first.");const res=await fetch("/api/admin/users",{method:"DELETE",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({userId:id})});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||"Unable to delete account.");return body;}
export async function getCloudExams(){if(!supabase)return [];const {data:{user}}=await supabase.auth.getUser();if(!user)return [];const {data,error}=await supabase.from("student_exams").select("exam,added_at").eq("user_id",user.id).order("added_at");if(error)throw error;return data||[];}
export async function addCloudExam(exam){if(!supabase)throw new Error("Cloud mode is not configured");const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in first.");const {error}=await supabase.from("student_exams").insert({user_id:user.id,exam});if(error&&error.code!=="23505")throw error;return getCloudExams();}
export async function removeCloudExam(exam){if(!supabase)throw new Error("Cloud mode is not configured");const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in first.");const exams=await getCloudExams();if(exams.length<=1)throw new Error("Keep at least one exam in your profile.");const {error}=await supabase.from("student_exams").delete().eq("user_id",user.id).eq("exam",exam);if(error)throw error;const profile=await getCloudProfile();if(profile?.exam===exam){const next=exams.find(x=>x.exam!==exam)?.exam;if(next)await supabase.from("profiles").update({exam:next}).eq("id",user.id);}return getCloudExams();}
export async function setActiveCloudExam(exam){if(!supabase)throw new Error("Cloud mode is not configured");const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in first.");const {data:membership,error:membershipError}=await supabase.from("student_exams").select("exam").eq("user_id",user.id).eq("exam",exam).maybeSingle();if(membershipError)throw membershipError;if(!membership)throw new Error("This exam is not in your profile.");const {data,error}=await supabase.from("profiles").update({exam}).eq("id",user.id).select(PROFILE_FIELDS).single();if(error)throw error;return data;}
export async function updateCloudProfile({name,dob}){if(!supabase)throw new Error("Cloud mode is not configured");const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in first.");const {data,error}=await supabase.from("profiles").update({name:name.trim(),dob:dob||null}).eq("id",user.id).select(PROFILE_FIELDS).single();if(error)throw error;return data;}
export async function syncAttempt(attempt){if(!supabase)return {cloud:false};const {data:{user}}=await supabase.auth.getUser();if(!user)return {cloud:false};const {error}=await supabase.from("attempts").insert({user_id:user.id,exam:attempt.exam,question_id:String(attempt.questionId),node_id:attempt.nodeId||null,selected:attempt.selected,answer:attempt.answer,correct:Boolean(attempt.correct),created_at:attempt.at});if(error)throw error;return {cloud:true};}
export async function upsertProgress(progress){if(!supabase)return {cloud:false};const {data:{user}}=await supabase.auth.getUser();if(!user)return {cloud:false};const {error}=await supabase.from("question_progress").upsert({user_id:user.id,exam:progress.exam,question_id:String(progress.questionId),attempts:progress.attempts,correct:progress.correct,mastery:progress.mastery,last_attempt_at:progress.lastAttemptAt});if(error)throw error;return {cloud:true};}
function questionToRow(q){return{id:String(q.id),exam:q.exam||"custom",stage:q.stage||null,year:q.year?Number(q.year):null,question:q.text||"",question_hi:q.textHi||null,options:q.options||[],options_hi:q.optionsHi||[],correct_option:q.correctOption||null,explanation_short:q.explanationShort||q.explanation||null,explanation_long:q.explanationLong||q.explanationDetailed||q.explanation||null,explanation_short_hi:q.explanationShortHi||null,explanation_long_hi:q.explanationLongHi||null,why_correct:q.whyCorrect||null,why_others_wrong:q.whyOthersWrong||{},key_fact:q.keyFact||null,key_fact_hi:q.keyFactHi||null,common_confusion:q.commonConfusion||q.commonTrap||null,subject:q.subject||null,topic:q.topic||null,subtopic:q.subtopic||null,concept:q.concept||null,node_id:q.nodeId||null,difficulty:q.difficulty||null,question_type:q.questionType||"MCQ",pyq:Boolean(q.pyq),source:q.source||null,verification_status:q.verificationStatus||"unverified",expected_time_sec:q.expectedTimeSec?Number(q.expectedTimeSec):60,updated_at:new Date().toISOString()};}
function rowToQuestion(r){const options=Array.isArray(r.options)?r.options:Object.values(r.options||{});const optionsHi=Array.isArray(r.options_hi)?r.options_hi:Object.values(r.options_hi||{});const answer=r.correct_option?String(r.correct_option).charCodeAt(0)-65:null;return{id:r.id,question_id:r.id,exam:r.exam,stage:r.stage||"",year:r.year||"",text:r.question||"",textHi:r.question_hi||"",options,optionsHi,answer:answer!=null&&answer>=0&&answer<options.length?answer:null,correctOption:r.correct_option||"",nodeId:r.node_id||"",subject:r.subject||"",topic:r.topic||"",subtopic:r.subtopic||"",concept:r.concept||"",explanation:r.explanation_short||r.explanation_long||"",explanationShort:r.explanation_short||"",explanationLong:r.explanation_long||"",explanationDetailed:r.explanation_long||"",explanationShortHi:r.explanation_short_hi||"",explanationLongHi:r.explanation_long_hi||"",whyCorrect:r.why_correct||"",whyOthersWrong:r.why_others_wrong||{},keyFact:r.key_fact||"",keyFactHi:r.key_fact_hi||"",commonConfusion:r.common_confusion||"",source:r.source||"",difficulty:r.difficulty||"",questionType:r.question_type||"MCQ",pyq:Boolean(r.pyq),verificationStatus:r.verification_status||"unverified",expectedTimeSec:r.expected_time_sec||60,updatedAt:r.updated_at,createdAt:r.created_at};}
export async function getCloudQuestions(){if(!supabase)return[];const {data,error}=await supabase.from("questions").select("*").order("created_at",{ascending:false});if(error)throw error;return(data||[]).map(rowToQuestion);}
export async function insertCloudQuestions(questions){if(!supabase)throw new Error("Cloud mode is not configured");if(!questions.length)return{inserted:0,duplicates:0};let inserted=0;for(let i=0;i<questions.length;i+=100){const chunk=questions.slice(i,i+100).map(questionToRow);const {data,error}=await supabase.from("questions").upsert(chunk,{onConflict:"id",ignoreDuplicates:true}).select("id");if(error)throw error;inserted+=(data||[]).length;}return{inserted,duplicates:questions.length-inserted};}
export async function updateCloudQuestion(id,patch){if(!supabase)throw new Error("Cloud mode is not configured");const row=questionToRow({...patch,id});delete row.id;const {data,error}=await supabase.from("questions").update(row).eq("id",id).select("*").single();if(error)throw error;return rowToQuestion(data);}
export async function deleteCloudQuestions(ids){if(!supabase)throw new Error("Cloud mode is not configured");if(!ids.length)return 0;const {data,error}=await supabase.from("questions").delete().in("id",ids).select("id");if(error)throw error;return(data||[]).length;}
