export const TREE = [
  {s:"Indian Polity & Constitution",topics:[{t:"Constitutional Framework",sub:["Basic Structure","Preamble","Fundamental Rights","DPSP","Fundamental Duties","Amendments"]},{t:"Union Executive",sub:["President","Vice President","Prime Minister","Council of Ministers","Attorney General"]},{t:"Parliament",sub:["Lok Sabha","Rajya Sabha","Legislative Process","Parliamentary Committees","Anti-Defection"]},{t:"Judiciary",sub:["Supreme Court","High Courts","Judicial Review","PIL","Judicial Activism"]},{t:"State Government",sub:["Governor","Chief Minister","State Legislature","State Council of Ministers"]},{t:"Local Government",sub:["Panchayati Raj","Municipalities","Urban Local Bodies","73rd & 74th Amendments"]},{t:"Constitutional Bodies",sub:["Election Commission","CAG","UPSC","Finance Commission","NCBC","NCSC"]},{t:"Federalism",sub:["Centre-State Relations","Inter-State Council","Zonal Councils","Centre's Emergency Powers"]}]},
  {s:"Indian History & Culture",topics:[{t:"Ancient India",sub:["Indus Valley","Vedic Age","Buddhism & Jainism","Maurya Empire","Gupta Empire"]},{t:"Medieval India",sub:["Delhi Sultanate","Mughal Empire","Bhakti Movement","Sufi Movement","Maratha Empire"]},{t:"Modern India",sub:["Advent of British","1857 Revolt","Indian National Movement","Gandhian Era","Partition"]},{t:"Art & Culture",sub:["Architecture","Painting","Music & Dance","Literature","Festivals"]}]},
  {s:"Rajasthan History & Culture",topics:[{t:"Early History",sub:["Rajput Dynasties","Prithviraj Chauhan","Mewar Dynasty","Marwar Dynasty"]},{t:"Freedom Struggle",sub:["1857 in Rajasthan","Praja Mandal Movement","Integration of Rajasthan","Role of Leaders"]},{t:"Art & Culture",sub:["Folk Dances","Folk Music","Paintings","Crafts","Fairs & Festivals"]},{t:"Architecture",sub:["Forts","Palaces","Temples","Step Wells"]}]},
  {s:"Indian Geography",topics:[{t:"Physical Geography",sub:["Physiography","Drainage System","Climate","Soils","Natural Vegetation"]},{t:"Economic Geography",sub:["Agriculture","Minerals","Industries","Transport","Energy"]},{t:"Human Geography",sub:["Population","Settlements","Migration","Literacy"]}]},
  {s:"Rajasthan Geography",topics:[{t:"Physical",sub:["Physiography","Desert","Aravalli Range","Drainage","Climate"]},{t:"Resources",sub:["Minerals","Soils","Irrigation","Forest Cover"]},{t:"Administrative",sub:["Districts","Divisions","Demographics","Livestock"]}]},
  {s:"Indian Economy",topics:[{t:"Basic Concepts",sub:["National Income","GDP & GVA","Inflation","Money Supply","Banking System"]},{t:"Public Finance",sub:["Union Budget","Tax Structure","Fiscal Policy","Government Schemes"]},{t:"Sectors",sub:["Agriculture","Industry","Services","External Sector","Balance of Payments"]},{t:"Financial Markets",sub:["RBI","Stock Market","Insurance","Pension System"]}]},
  {s:"Rajasthan Economy",topics:[{t:"State Finance",sub:["State Budget","Tax Revenue","Plan Outlay","Flagship Schemes"]},{t:"Sectors",sub:["Agriculture","Industries","Tourism","Handicrafts","Power Sector"]},{t:"Development",sub:["Rajasthan Model","Investment Potential","MSME","Skill Development"]}]},
  {s:"Science & Technology",topics:[{t:"Physical Sciences",sub:["Physics Basics","Chemistry Basics","Space Technology","Nuclear Science"]},{t:"Life Sciences",sub:["Biology Basics","Human Health","Biotechnology","Diseases & Vaccines"]},{t:"IT & Digital",sub:["Digital India","AI & ML","Cybersecurity","E-Governance"]},{t:"Defence & Space",sub:["ISRO Missions","DRDO","Defence Systems","Nuclear Program"]}]},
  {s:"Environment & Ecology",topics:[{t:"Ecology",sub:["Ecosystems","Biodiversity","Food Chains","Conservation"]},{t:"Environmental Issues",sub:["Pollution","Climate Change","Global Warming","Waste Management"]},{t:"Conservation",sub:["Wildlife Protection","National Parks","Tiger Reserves","Biosphere Reserves"]},{t:"Policies & Laws",sub:["Environmental Clearance","Forest Act","Wildlife Act","Paris Agreement"]}]},
  {s:"Current Affairs",topics:[{t:"National Affairs",sub:["Government Schemes","Policy Changes","Judgments","Elections"]},{t:"International Affairs",sub:["Foreign Policy","Treaties","UN & Global Bodies","Geopolitics"]},{t:"Rajasthan Affairs",sub:["State Policies","Schemes","Appointments","Key Events"]},{t:"Sports & Awards",sub:["Sports Events","Awards & Honours","Books & Authors","Obituaries"]}]},
  {s:"Reasoning & Mental Ability",topics:[{t:"Verbal Reasoning",sub:["Analogy","Classification","Series","Coding-Decoding","Blood Relations"]},{t:"Non-Verbal",sub:["Mirror Images","Paper Folding","Embedded Figures","Pattern Completion"]},{t:"Quantitative",sub:["Number System","Percentage","Ratio","Time & Work","Data Interpretation"]}]},
  {s:"Public Administration",topics:[{t:"Administrative Theory",sub:["Principles","Organisation","Good Governance","Accountability"]},{t:"Rajasthan Administration",sub:["State Secretariat","District Administration","Panchayati Raj","Urban Administration"]},{t:"Civil Services",sub:["RAS Examination","Role of RAS Officer","Ethics in Administration","RTI"]},{t:"Public Policy",sub:["Policy Formulation","Implementation","Evaluation","Citizen-Centric Administration"]}]},
  {s:"Ethics & Integrity",topics:[{t:"Ethics Basics",sub:["Ethical Theories","Values","Integrity","Probity in Governance"]},{t:"Case Studies",sub:["Administrative Dilemmas","Conflict of Interest","Corruption","Whistleblowing"]},{t:"Aptitude",sub:["Emotional Intelligence","Attitude","Leadership","Decision Making"]}]},
  {s:"International Relations",topics:[{t:"India's Foreign Policy",sub:["Non-Alignment","Neighborhood Policy","Look East/Act East"]},{t:"Major Powers",sub:["India-US","India-Russia","India-China","India-EU"]},{t:"Multilateral",sub:["UNO","SAARC","BRICS","WTO","G20"]}]},
  {s:"Social Issues & Schemes",topics:[{t:"Social Sector",sub:["Education","Health","Women & Child","Poverty","Employment"]},{t:"Welfare Schemes",sub:["Central Schemes","Rajasthan Schemes","Subsidies","Social Security"]},{t:"Vulnerable Groups",sub:["SC/ST","OBC","Minorities","Persons with Disabilities","Senior Citizens"]}]}
];

export const ALL_SUBJECTS = TREE.map(x => x.s);
export function tagKey(subject, topic, subtopic) { return subtopic ? `${subject}|${topic}|${subtopic}` : `${subject}|${topic}`; }
export function findSyllabusNode(subject, topic, subtopic) {
  const s = TREE.find(x => x.s === subject); if (!s) return null;
  const t = s.topics.find(x => x.t === topic); if (!t) return null;
  if (subtopic && !t.sub.includes(subtopic)) return null;
  return {subject:s, topic:t};
}
export function validTags() {
  const out = new Set();
  TREE.forEach(s => s.topics.forEach(t => { out.add(tagKey(s.s,t.t)); t.sub.forEach(st => out.add(tagKey(s.s,t.t,st))); }));
  return out;
}
