import {createClient} from "@supabase/supabase-js";
import {NextResponse} from "next/server";

function config(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;const service=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!anon||!service)throw new Error("Server cloud configuration is incomplete.");return {url,anon,service};}
async function auth(request){const {url,anon,service}=config();const token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)throw new Error("Authentication required.");const pub=createClient(url,anon,{auth:{autoRefreshToken:false,persistSession:false}});const {data:{user},error}=await pub.auth.getUser(token);if(error||!user)throw new Error("Invalid or expired session.");return {user,db:createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}})};}
async function rank(db,testId,score){const {data,error}=await db.from("test_attempts").select("score").eq("test_id",testId).not("submitted_at","is",null).order("score",{ascending:false});if(error)throw error;const scores=(data||[]).map(x=>Number(x.score));return scores.findIndex(x=>x<=Number(score))+1;}

export async function GET(request,{params}){try{const {user,db}=await auth(request);const id=params.id;const {data:test,error}=await db.from("tests").select("id,exam,title,description,start_at,end_at,duration_sec,status").eq("id",id).maybeSingle();if(error)throw error;if(!test)return NextResponse.json({error:"Test not found."},{status:404});const {data:attempt,error:ae}=await db.from("test_attempts").select("id,started_at,submitted_at,score,correct,wrong,unanswered,total").eq("test_id",id).eq("user_id",user.id).maybeSingle();if(ae)throw ae;const now=Date.now();if(attempt?.submitted_at&&new Date(test.end_at).getTime()<=now){return NextResponse.json({mode:"result",test,attempt,rank:await rank(db,id,attempt.score)});}
if(now<new Date(test.start_at).getTime()||now>=new Date(test.end_at).getTime())return NextResponse.json({mode:"waiting",test,attempt:attempt||null});
if(attempt?.submitted_at)return NextResponse.json({mode:"result",test,attempt,rank:await rank(db,id,attempt.score)});
const {data:tq,error:qe}=await db.from("test_questions").select("question_id,order_no").eq("test_id",id).order("order_no");if(qe)throw qe;const qids=(tq||[]).map(x=>x.question_id);const {data:questions,error:qerr}=await db.from("questions").select("id,question,question_hi,options,options_hi,node_id,subject,topic,subtopic,concept,difficulty,question_type").in("id",qids);if(qerr)throw qerr;const byId=new Map((questions||[]).map(q=>[q.id,q]));const safe=(tq||[]).map(x=>byId.get(x.question_id)).filter(Boolean);return NextResponse.json({mode:"live",test,attempt:attempt||null,questions:safe.map(q=>({...q,options:Array.isArray(q.options)?q.options:Object.values(q.options||{}),options_hi:Array.isArray(q.options_hi)?q.options_hi:Object.values(q.options_hi||{})}))});}catch(e){return NextResponse.json({error:e?.message||"Unable to load test."},{status:401});}}

export async function POST(request,{params}){try{const {user,db}=await auth(request);const id=params.id;const body=await request.json().catch(()=>({}));const answers=body.answers&&typeof body.answers==="object"?body.answers:{};const {data:test,error}=await db.from("tests").select("id,exam,title,start_at,end_at,duration_sec,status").eq("id",id).maybeSingle();if(error)throw error;if(!test)return NextResponse.json({error:"Test not found."},{status:404});const now=new Date();if(test.status!=="published")return NextResponse.json({error:"This test is not live."},{status:400});const {data:existing,error:ee}=await db.from("test_attempts").select("*").eq("test_id",id).eq("user_id",user.id).maybeSingle();if(ee)throw ee;if(existing?.submitted_at)return NextResponse.json({ok:true,attempt:existing,rank:await rank(db,id,existing.score)});
if(now<new Date(test.start_at)||now>new Date(test.end_at))return NextResponse.json({error:"The live period has ended or has not started."},{status:400});
const {data:tq,error:qe}=await db.from("test_questions").select("question_id,order_no").eq("test_id",id).order("order_no");if(qe)throw qe;const ids=(tq||[]).map(x=>x.question_id);const {data:questions,error:qerr}=await db.from("questions").select("id,correct_option").in("id",ids);if(qerr)throw qerr;const correctMap=new Map((questions||[]).map(q=>[q.id,String(q.correct_option||"").toUpperCase().charCodeAt(0)-65]));const total=ids.length;let correct=0,wrong=0,unanswered=0;const rows=ids.map(qid=>{const raw=answers[qid];const selected=raw===null||raw===undefined||raw===""?null:Number(raw);const c=correctMap.get(qid);const ok=selected!==null&&Number.isInteger(selected)&&selected===c;if(selected===null||!Number.isInteger(selected))unanswered++;else if(ok)correct++;else wrong++;return{question_id:qid,selected:ok||selected===null||Number.isInteger(selected)?selected:null,correct:ok};});const score=Number((correct-(wrong*0.25)).toFixed(2));let attempt=existing;if(!attempt){const {data:a,error:ae}=await db.from("test_attempts").insert({test_id:id,user_id:user.id,started_at:body.startedAt||now.toISOString(),submitted_at:now.toISOString(),score,correct,wrong,unanswered,total}).select("*").single();if(ae)throw ae;attempt=a;}else{const {data:a,error:ae}=await db.from("test_attempts").update({submitted_at:now.toISOString(),score,correct,wrong,unanswered,total}).eq("id",attempt.id).select("*").single();if(ae)throw ae;attempt=a;}const {error:ansErr}=await db.from("test_answers").upsert(rows.map(r=>({...r,attempt_id:attempt.id})));if(ansErr)throw ansErr;return NextResponse.json({ok:true,attempt,rank:await rank(db,id,score)});}catch(e){return NextResponse.json({error:e?.message||"Unable to submit test."},{status:400});}}
