"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {EXAM_PROFILES} from "../lib/exams";
import {getCloudProfile,getCloudProfiles,getCloudAdminAttempts,updateCloudUserRole,deleteCloudUser} from "../lib/supabase";
const card={background:"#fff",border:"1px solid #dfe5ed",borderRadius:14,padding:18,marginBottom:16};
const btn={border:"1px solid #cfd7e3",borderRadius:9,padding:"8px 12px",background:"#fff",cursor:"pointer"};
export default function Admin(){
 const router=useRouter();const[profile,setProfile]=useState(null),[users,setUsers]=useState([]),[history,setHistory]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 async function load(){setLoading(true);setMessage("");try{const p=await getCloudProfile();if(!p||p.role!=="admin"){router.replace("/");return;}setProfile(p);const[a,b]=await Promise.all([getCloudProfiles(),getCloudAdminAttempts()]);setUsers(a);setHistory(b);if(selected)setSelected(a.find(x=>x.id===selected.id)||null);}catch(e){setMessage(e?.message||"Unable to load admin data.");}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const rows=useMemo(()=>users.map(u=>{const a=history.filter(x=>x.user_id===u.id),c=a.filter(x=>x.correct).length;return{...u,attempts:a.length,accuracy:a.length?Math.round(c/a.length*100):0,last:a[0]?.created_at||null};}),[users,history]);
 const detail=selected?history.filter(x=>x.user_id===selected.id):[];
 const concepts=useMemo(()=>{const m={};detail.forEach(a=>{const k=a.node_id||"unmapped";m[k]??={attempts:0,correct:0};m[k].attempts++;if(a.correct)m[k].correct++;});return Object.entries(m).map(([node,x])=>({node,...x,accuracy:Math.round(x.correct/x.attempts*100)})).sort((a,b)=>a.accuracy-b.accuracy);},[detail]);
 async function role(u,role){if(u.id===profile?.id||u.role==="admin"){setMessage("Admin accounts cannot be changed here.");return;}try{const x=await updateCloudUserRole(u.id,role);setUsers(v=>v.map(y=>y.id===u.id?x:y));if(selected?.id===u.id)setSelected(x);setMessage(`${u.name} is now ${role}.`);}catch(e){setMessage(e?.message||"Unable to change role.");}}
 async function remove(u){if(u.id===profile?.id||u.role==="admin")return;if(!window.confirm(`Delete ${u.name} (${u.user_id})? This permanently removes the account and its learning data.`))return;try{setMessage("Deleting account…");await deleteCloudUser(u.id);setUsers(v=>v.filter(x=>x.id!==u.id));setHistory(v=>v.filter(x=>x.user_id!==u.id));if(selected?.id===u.id)setSelected(null);setMessage(`${u.name} was deleted.`);}catch(e){setMessage(e?.message||"Unable to delete account.");}}
 if(loading)return <main style={{padding:30,fontFamily:"system-ui"}}>Loading admin control…</main>;
 return <main style={{minHeight:"100vh",background:"#f6f8fb",color:"#172033",fontFamily:"system-ui"}}><div style={{maxWidth:1150,margin:"0 auto",padding:24}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><a href="/">← Dashboard</a><h1 style={{marginBottom:4}}>Admin Control</h1><p style={{marginTop:0,color:"#58657a"}}>Shared cloud administration.</p></div><div style={{display:"flex",gap:8}}><button style={btn} onClick={()=>router.push("/question-bank")}>Question Bank</button><button style={btn} onClick={()=>router.push("/question-import")}>AI Import</button><button style={btn} onClick={load}>Refresh</button></div></div>
  {message&&<div style={{...card,padding:12}}>{message}</div>}
  <section style={card}><h2 style={{marginTop:0}}>User management</h2><p style={{color:"#58657a"}}>Manage cloud accounts, staff roles and access. Account deletion is permanent.</p>
   {rows.length?<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:780}}><thead><tr>{["User","Exam","Role","Attempts","Accuracy","Actions"].map(x=><th key={x} style={{textAlign:"left",padding:10}}>{x}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.id} style={{borderTop:"1px solid #edf0f4"}}><td style={{padding:10}}><b>{s.name}</b><br/><small>{s.user_id}</small></td><td style={{padding:10}}>{EXAM_PROFILES[s.exam]?.shortName||s.exam}</td><td style={{padding:10}}><select value={s.role} onChange={e=>role(s,e.target.value)} disabled={s.role==="admin"} style={{padding:7,borderRadius:8,border:"1px solid #ccd5e1"}}><option value="student">Student</option><option value="mentor">Mentor</option><option value="admin">Admin</option></select></td><td style={{padding:10}}>{s.attempts}</td><td style={{padding:10}}>{s.accuracy}%</td><td style={{padding:10}}><button style={{...btn,marginRight:6}} onClick={()=>setSelected(s)}>View</button>{s.role!=="admin"&&<button style={btn} onClick={()=>remove(s)}>Delete</button>}</td></tr>)}</tbody></table></div>:<p>No cloud profiles found.</p>}
  </section>
  {selected&&<section style={card}><div style={{display:"flex",justifyContent:"space-between"}}><div><h2 style={{marginTop:0}}>{selected.name}</h2><p>{selected.user_id} • {EXAM_PROFILES[selected.exam]?.shortName||selected.exam} • {selected.role}</p></div><button style={btn} onClick={()=>setSelected(null)}>Close</button></div><p><b>{detail.length}</b> attempts • <b>{detail.length?Math.round(detail.filter(x=>x.correct).length/detail.length*100):0}%</b> accuracy</p><h3>Priority concepts</h3>{concepts.length?concepts.slice(0,12).map(c=><div key={c.node} style={{display:"flex",justifyContent:"space-between",padding:"9px 0",borderBottom:"1px solid #edf0f4"}}><span>{c.node}<br/><small>{c.attempts} attempt(s)</small></span><b>{c.accuracy}%</b></div>):<p>No attempts yet.</p>}</section>}
 </div></main>;
}