"use client";
import {useEffect,useState} from "react";
const btn={padding:"8px 12px",borderRadius:8,border:"1px solid #ccd4df",background:"#fff",color:"#172033",cursor:"pointer",fontWeight:600};
const danger={...btn,borderColor:"#f1b5b5",color:"#b42318"};
export default function QuestionBank(){
 const[qs,setQs]=useState([]),[q,setQ]=useState(""),[editing,setEditing]=useState(null),[draft,setDraft]=useState(""),[selected,setSelected]=useState(new Set());
 function load(){try{setQs(JSON.parse(localStorage.getItem("adaptive-question-bank")||"[]"));setSelected(new Set())}catch{setQs([]);setSelected(new Set())}}
 useEffect(load,[]);
 function startEdit(x){setEditing(x.id);setDraft(x.explanation||x.explanationShort||"")}
 function saveExplanation(id){const updated=qs.map(x=>x.id===id?{...x,explanation:draft.trim(),explanationShort:draft.trim(),explanationEditedAt:new Date().toISOString()}:x);localStorage.setItem("adaptive-question-bank",JSON.stringify(updated));setQs(updated);setEditing(null);setDraft("")}
 function toggle(id){setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 function toggleAll(){setSelected(selected.size===shown.length?new Set():new Set(shown.map(x=>x.id)))}
 function deleteSelected(){if(!selected.size)return;if(!window.confirm(`Delete ${selected.size} selected question${selected.size===1?"":"s"}? This cannot be undone.`))return;const updated=qs.filter(x=>!selected.has(x.id));localStorage.setItem("adaptive-question-bank",JSON.stringify(updated));setQs(updated);setSelected(new Set());setEditing(null);setDraft("")}
 const shown=qs.filter(x=>(x.text||"").toLowerCase().includes(q.toLowerCase())||(x.nodeId||"").toLowerCase().includes(q.toLowerCase()));
 const allShownSelected=shown.length>0&&selected.size===shown.length&&shown.every(x=>selected.has(x.id));
 return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui,-apple-system,sans-serif",color:"#172033"}}><div style={{maxWidth:1100,margin:"0 auto",padding:24}}><a href="/">← Dashboard</a><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><h1>Question Bank</h1><p>Validated and concept-linked questions imported into this browser.</p></div><a href="/question-import">＋ Import</a></div>
 <div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",marginBottom:10}}><button style={btn} onClick={toggleAll} disabled={!shown.length}>{allShownSelected?"Clear selection":"Select all shown"}</button><span style={{fontSize:13,color:"#667085"}}>{selected.size} selected</span><button style={danger} onClick={deleteSelected} disabled={!selected.size}>Delete selected</button></div>
 <input value={q} onChange={e=>{setQ(e.target.value);setSelected(new Set())}} placeholder="Search question or concept…" style={{width:"100%",boxSizing:"border-box",padding:12,border:"1px solid #ccd4df",borderRadius:9}}/>
 <p>{shown.length} shown • {qs.length} total</p>
 {shown.map((x,i)=><article key={x.id} style={{background:"white",border:`1px solid ${selected.has(x.id)?"#172033":"#dfe5ed"}`,borderRadius:12,padding:16,marginBottom:10}}><div style={{display:"flex",gap:12,alignItems:"flex-start"}}><input aria-label={`Select question ${i+1}`} type="checkbox" checked={selected.has(x.id)} onChange={()=>toggle(x.id)} style={{marginTop:4,width:18,height:18}}/><div style={{flex:1}}><b>{i+1}. {x.text}</b><div style={{fontSize:12,color:"#667085",marginTop:6}}>{x.exam} • {x.nodeId} • {x.difficulty} • {x.tags?.join(" · ")}</div><details style={{marginTop:8}} open={editing===x.id}><summary>Explanation</summary>{editing===x.id?<div style={{marginTop:10}}><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Write a clear explanation for why the correct answer is correct…" rows={6} style={{width:"100%",boxSizing:"border-box",padding:11,border:"1px solid #ccd4df",borderRadius:9,fontFamily:"inherit",fontSize:14,lineHeight:1.5}}/><div style={{display:"flex",gap:8,marginTop:8}}><button style={btn} onClick={()=>saveExplanation(x.id)}>Save explanation</button><button style={btn} onClick={()=>{setEditing(null);setDraft("")}}>Cancel</button></div></div>:<><p>{x.explanation||x.explanationShort||"No explanation supplied."}</p><button style={btn} onClick={()=>startEdit(x)}>{x.explanation||x.explanationShort?"Edit explanation":"＋ Add explanation"}</button><p><b>Key fact:</b> {x.keyFact||"—"}</p></>}</details></div></div></article>)}
 </div></main>;
}