"use client";
import {useEffect,useState} from "react";
const btn={padding:"8px 12px",borderRadius:8,border:"1px solid #ccd4df",background:"#fff",color:"#172033",cursor:"pointer",fontWeight:600};
export default function QuestionBank(){
 const[qs,setQs]=useState([]),[q,setQ]=useState(""),[editing,setEditing]=useState(null),[draft,setDraft]=useState("");
 function load(){try{setQs(JSON.parse(localStorage.getItem("adaptive-question-bank")||"[]"))}catch{setQs([])}}
 useEffect(load,[]);
 function startEdit(x){setEditing(x.id);setDraft(x.explanation||"")}
 function saveExplanation(id){
  const updated=qs.map(x=>x.id===id?{...x,explanation:draft.trim(),explanationEditedAt:new Date().toISOString()}:x);
  localStorage.setItem("adaptive-question-bank",JSON.stringify(updated));setQs(updated);setEditing(null);setDraft("");
 }
 const shown=qs.filter(x=>(x.text||"").toLowerCase().includes(q.toLowerCase())||(x.nodeId||"").toLowerCase().includes(q.toLowerCase()));
 return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui,-apple-system,sans-serif",color:"#172033"}}><div style={{maxWidth:1100,margin:"0 auto",padding:24}}><a href="/">← Dashboard</a><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><h1>Question Bank</h1><p>Validated and concept-linked questions imported into this browser.</p></div><a href="/question-import">＋ Import</a></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search question or concept…" style={{width:"100%",boxSizing:"border-box",padding:12,border:"1px solid #ccd4df",borderRadius:9}}/><p>{shown.length} shown • {qs.length} total</p>{shown.map((x,i)=><article key={x.id} style={{background:"white",border:"1px solid #dfe5ed",borderRadius:12,padding:16,marginBottom:10}}><b>{i+1}. {x.text}</b><div style={{fontSize:12,color:"#667085",marginTop:6}}>{x.exam} • {x.nodeId} • {x.difficulty} • {x.tags?.join(" · ")}</div><details style={{marginTop:8}} open={editing===x.id}><summary>Explanation</summary>{editing===x.id?<div style={{marginTop:10}}><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Write a clear explanation for why the correct answer is correct…" rows={6} style={{width:"100%",boxSizing:"border-box",padding:11,border:"1px solid #ccd4df",borderRadius:9,fontFamily:"inherit",fontSize:14,lineHeight:1.5}}/><div style={{display:"flex",gap:8,marginTop:8}}><button style={btn} onClick={()=>saveExplanation(x.id)}>Save explanation</button><button style={btn} onClick={()=>{setEditing(null);setDraft("")}}>Cancel</button></div></div>:<><p>{x.explanation||"No explanation supplied."}</p><button style={btn} onClick={()=>startEdit(x)}>{x.explanation?"Edit explanation":"＋ Add explanation"}</button><p><b>Key fact:</b> {x.keyFact||"—"}</p></>}</details></article>)}</div></main>}
