"use client";
import {useEffect,useMemo,useState} from "react";
import {EXAM_PROFILES,DEFAULT_EXAM} from "./lib/exams";
import {PREDEFINED_SYLLABUS,SYLLABUS_META} from "./lib/predefinedSyllabus";

const css={page:{minHeight:"100vh",background:"#f6f8fb",color:"#172033",fontFamily:"system-ui,-apple-system,sans-serif"},wrap:{maxWidth:1200,margin:"0 auto",padding:24},btn:{border:"1px solid #ccd4df",background:"white",borderRadius:8,padding:"9px 13px",cursor:"pointer"},primary:{background:"#172033",color:"white",border:"1px solid #172033",borderRadius:8,padding:"9px 13px",cursor:"pointer"},card:{background:"white",border:"1px solid #dfe5ed",borderRadius:12,padding:18,marginBottom:14},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12},input:{width:"100%",boxSizing:"border-box",padding:10,border:"1px solid #ccd4df",borderRadius:8},small:{fontSize:12,color:"#667085"}};

export default function Home(){
 const [user,setUser]=useState(null),[loginId,setLoginId]=useState(""),[loginPw,setLoginPw]=useState(""),[signup,setSignup]=useState(false),[name,setName]=useState(""),[message,setMessage]=useState("");
 const [exam,setExam]=useState(DEFAULT_EXAM),[tab,setTab]=useState("dashboard"),[query,setQuery]=useState(""),[expanded,setExpanded]=useState(new Set());
 useEffect(()=>{try{const u=JSON.parse(localStorage.getItem("adaptive-user")||"null");if(u)setUser(u)}catch{}},[]);
 const examNodes=useMemo(()=>PREDEFINED_SYLLABUS.filter(n=>n.exam===exam),[exam]);
 const counts=useMemo(()=>({subjects:examNodes.filter(n=>n.level==="subject").length,topics:examNodes.filter(n=>n.level==="topic").length,concepts:examNodes.filter(n=>n.level==="concept").length}),[examNodes]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?examNodes.filter(n=>(n.title+" "+n.nodeId+" "+n.level).toLowerCase().includes(q)):examNodes},[examNodes,query]);
 const tree=useMemo(()=>{const m={},r=[];examNodes.forEach(n=>m[n.nodeId]={...n,children:[]});examNodes.forEach(n=>n.parentId&&m[n.parentId]?m[n.parentId].children.push(m[n.nodeId]):r.push(m[n.nodeId]));return r},[examNodes]);
 function login(){const users=JSON.parse(localStorage.getItem("adaptive-users")||"{}");if(signup){if(!loginId.trim()||!loginPw){setMessage("Enter user ID and password.");return}if(users[loginId]){setMessage("User ID already exists.");return}const u={id:loginId.trim(),name:name.trim()||loginId.trim(),password:loginPw};users[u.id]=u;localStorage.setItem("adaptive-users",JSON.stringify(users));localStorage.setItem("adaptive-user",JSON.stringify(u));setUser(u);setMessage("Account created.")}else{const u=users[loginId];if(!u||u.password!==loginPw){setMessage("Invalid credentials.");return}localStorage.setItem("adaptive-user",JSON.stringify(u));setUser(u);setMessage("Welcome back, "+u.name+"!")}}
 function logout(){localStorage.removeItem("adaptive-user");setUser(null)}
 function node(n,d=0){const open=expanded.has(n.nodeId);return <div key={n.nodeId}><div onClick={()=>n.children.length&&setExpanded(s=>{const x=new Set(s);x.has(n.nodeId)?x.delete(n.nodeId):x.add(n.nodeId);return x})} style={{display:"flex",gap:8,alignItems:"center",padding:"9px 4px",paddingLeft:d*20,borderBottom:"1px solid #edf0f4",cursor:n.children.length?"pointer":"default"}}><span style={{width:14}}>{n.children.length?(open?"▾":"▸"):""}</span><span style={{fontWeight:n.level==="subject"?700:n.level==="topic"?600:400}}>{n.title}</span><span style={{...css.small,marginLeft:"auto"}}>{n.level}</span></div>{open&&n.children.map(c=>node(c,d+1))}</div>}
 if(!user)return <main style={css.page}><div style={{...css.wrap,maxWidth:420,paddingTop:80}}><div style={{...css.card,textAlign:"center"}}><b>ADAPTIVE SYLLABUS</b><h1>{signup?"Create account":"Sign in"}</h1>{message&&<p>{message}</p>}{signup&&<input style={{...css.input,marginBottom:10}} placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/>}<input style={{...css.input,marginBottom:10}} placeholder="User ID" value={loginId} onChange={e=>setLoginId(e.target.value)}/><input style={{...css.input,marginBottom:12}} type="password" placeholder="Password" value={loginPw} onChange={e=>setLoginPw(e.target.value)} onKeyDown={e=>e.key==="Enter"&&login()}/><button style={{...css.primary,width:"100%"}} onClick={login}>{signup?"Create account":"Sign in"}</button><button style={{...css.btn,width:"100%",marginTop:10}} onClick={()=>{setSignup(!signup);setMessage("")}}>{signup?"Already have an account? Sign in":"Need an account? Sign up"}</button></div></div></main>;
 return <main style={css.page}><div style={css.wrap}><header style={{display:"flex",justifyContent:"space-between",alignItems:"start"}}><div><b>ADAPTIVE SYLLABUS</b><h1 style={{margin:"6px 0"}}>Your learning system</h1><span style={css.small}>Multi-exam • concept-level • live syllabus source</span></div><div><span style={css.small}>{user.name}</span> <button style={css.btn} onClick={logout}>Logout</button></div></header>
 <div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"18px 0"}}>{Object.values(EXAM_PROFILES).map(e=><button key={e.id} style={exam===e.id?css.primary:css.btn} onClick={()=>{setExam(e.id);setTab("dashboard")}}>{e.shortName}</button>)}</div>
 <div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:18}}>{[["dashboard","Dashboard"],["syllabus","Syllabus"],["bank","Concept search"]].map(([id,label])=><button key={id} style={tab===id?css.primary:css.btn} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {message&&<div style={{...css.card,background:"#f0f7ff"}}>{message}</div>}
 {tab==="dashboard"&&<><div style={css.grid}>{[["Subjects",counts.subjects],["Topics",counts.topics],["Concepts",counts.concepts],["Total nodes",examNodes.length]].map(([a,b])=><section key={a} style={css.card}><div style={css.small}>{a}</div><div style={{fontSize:30,fontWeight:700}}>{b}</div></section>)}</div><section style={css.card}><h2>{SYLLABUS_META[exam]?.label||EXAM_PROFILES[exam]?.name||exam}</h2><p style={css.small}>The dashboard now reads the same expanded concept-level syllabus used by the explorer. No duplicate hard-coded syllabus remains here.</p><button style={css.primary} onClick={()=>setTab("syllabus")}>Open full syllabus</button></section></>}
 {tab==="syllabus"&&<section style={css.card}><h2>Concept-Level Syllabus</h2><div style={css.small}>{counts.subjects} subjects • {counts.topics} topics • {counts.concepts} concepts • {examNodes.length} total nodes</div><div style={{display:"flex",gap:8,margin:"12px 0"}}><button style={css.btn} onClick={()=>setExpanded(new Set(examNodes.map(n=>n.nodeId)))}>Expand all</button><button style={css.btn} onClick={()=>setExpanded(new Set())}>Collapse all</button></div>{tree.map(n=>node(n))}</section>}
 {tab==="bank"&&<section style={css.card}><h2>Search syllabus concepts</h2><input style={css.input} placeholder="Search subject, topic or concept…" value={query} onChange={e=>setQuery(e.target.value)}/><div style={{marginTop:12}}>{filtered.slice(0,150).map(n=><div key={n.nodeId} style={{padding:"9px 4px",borderBottom:"1px solid #edf0f4"}}><b>{n.title}</b><div style={css.small}>{n.level} • {n.nodeId}</div></div>)}</div></section>}
 </div></main>;
}
