"use client";
import {useEffect,useState} from "react";
import {EXAM_PROFILES} from "../lib/exams";
import {getCloudProfile,updateCloudProfile} from "../lib/supabase";
const input={width:"100%",boxSizing:"border-box",padding:11,border:"1px solid #ccd4df",borderRadius:9};
const btn={border:"1px solid #ccd4df",background:"white",borderRadius:9,padding:"10px 14px",cursor:"pointer",textDecoration:"none",color:"inherit"};
const primary={...btn,background:"#172033",color:"white",borderColor:"#172033"};
export default function Profile(){
 const[profile,setProfile]=useState(null),[name,setName]=useState(""),[dob,setDob]=useState(""),[exam,setExam]=useState("ras"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{try{const p=await getCloudProfile();if(p){setProfile(p);setName(p.name||"");setDob(p.dob||"");setExam(p.exam||"ras");}else setMessage("Please sign in first.");}catch(e){setMessage(e?.message||"Unable to load profile.");}})();},[]);
 async function save(){setMessage("");if(!name.trim()||!dob||!exam){setMessage("Please complete your name, date of birth and exam.");return;}setBusy(true);try{const p=await updateCloudProfile({name,dob,exam});setProfile(p);localStorage.setItem("adaptive-user",JSON.stringify(p));setMessage("Profile updated successfully.");}catch(e){setMessage(e?.message||"Unable to update profile.");}finally{setBusy(false);}}
 if(!profile)return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui",color:"#172033",padding:24}}><a href="/" style={btn}>← Dashboard</a><section style={{maxWidth:520,margin:"30px auto",background:"white",border:"1px solid #dfe5ed",borderRadius:14,padding:20}}><h1>Edit profile</h1><p>{message||"Loading…"}</p></section></main>;
 return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui",color:"#172033",padding:24}}><div style={{maxWidth:620,margin:"0 auto"}}><a href="/" style={btn}>← Dashboard</a><section style={{background:"white",border:"1px solid #dfe5ed",borderRadius:14,padding:20,marginTop:18}}><h1>Edit profile</h1><p style={{fontSize:13,color:"#667085"}}>Correct your personal details anytime. Your User ID cannot be changed here.</p>{message&&<div style={{padding:12,borderRadius:9,background:"#f0f7ff",marginBottom:14}}>{message}</div>}<label>Name</label><input style={{...input,margin:"6px 0 14px"}} value={name} onChange={e=>setName(e.target.value)}/><label>Date of birth</label><input type="date" style={{...input,margin:"6px 0 14px"}} value={dob} onChange={e=>setDob(e.target.value)}/><label>Exam</label><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"6px 0 18px"}}>{Object.values(EXAM_PROFILES).filter(e=>e.id!=="custom").map(e=><button key={e.id} type="button" onClick={()=>setExam(e.id)} style={exam===e.id?primary:btn}>{e.shortName}</button>)}</div><button disabled={busy} onClick={save} style={{...primary,opacity:busy?.7:1}}>{busy?"Saving…":"Save changes"}</button></section></div></main>;
}
