"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {EXAM_PROFILES} from "../lib/exams";
import {getCloudProfile,getCloudExams,addCloudExam,removeCloudExam,setActiveCloudExam,updateCloudProfile,cloudSignOut} from "../lib/supabase";
const input={width:"100%",boxSizing:"border-box",padding:11,border:"1px solid #ccd4df",borderRadius:9};
const btn={border:"1px solid #ccd4df",background:"white",borderRadius:9,padding:"10px 14px",cursor:"pointer",textDecoration:"none",color:"inherit"};
const primary={...btn,background:"#172033",color:"white",borderColor:"#172033"};
export default function Profile(){
 const router=useRouter();
 const[profile,setProfile]=useState(null),[name,setName]=useState(""),[dob,setDob]=useState(""),[exams,setExams]=useState([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{const p=await getCloudProfile();if(!p){setMessage("Please sign in first.");return;}setProfile(p);setName(p.name||"");setDob(p.dob||"");setExams(await getCloudExams());}catch(e){setMessage(e?.message||"Unable to load profile.");}}
 useEffect(()=>{load();},[]);
 async function save(){setMessage("");if(!name.trim()||!dob){setMessage("Please complete your name and date of birth.");return;}setBusy(true);try{const p=await updateCloudProfile({name,dob});setProfile(p);localStorage.setItem("adaptive-user",JSON.stringify(p));setMessage("Profile updated successfully.");}catch(e){setMessage(e?.message||"Unable to update profile.");}finally{setBusy(false);}}
 async function switchExam(id){setBusy(true);setMessage("");try{const p=await setActiveCloudExam(id);setProfile(p);localStorage.setItem("adaptive-user",JSON.stringify(p));setMessage(`${EXAM_PROFILES[id]?.shortName||id} is now your active exam.`);}catch(e){setMessage(e?.message||"Unable to switch exam.");}finally{setBusy(false);}}
 async function addExam(id){setBusy(true);setMessage("");try{const rows=await addCloudExam(id);setExams(rows);setMessage(`${EXAM_PROFILES[id]?.shortName||id} added to your profile.`);}catch(e){setMessage(e?.message||"Unable to add exam.");}finally{setBusy(false);}}
 async function removeExam(id){if(exams.length<=1)return; if(!confirm(`Remove ${EXAM_PROFILES[id]?.shortName||id} from your profile?`))return;setBusy(true);setMessage("");try{const rows=await removeCloudExam(id);setExams(rows);const p=await getCloudProfile();setProfile(p);localStorage.setItem("adaptive-user",JSON.stringify(p));setMessage(`${EXAM_PROFILES[id]?.shortName||id} removed.`);}catch(e){setMessage(e?.message||"Unable to remove exam.");}finally{setBusy(false);}}
 async function logout(){await cloudSignOut();localStorage.removeItem("adaptive-user");router.replace("/");}
 if(!profile)return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui",color:"#172033",padding:24}}><a href="/" style={btn}>← Dashboard</a><section style={{maxWidth:620,margin:"30px auto",background:"white",border:"1px solid #dfe5ed",borderRadius:14,padding:20}}><h1>My profile</h1><p>{message||"Loading…"}</p></section></main>;
 const ids=exams.map(x=>x.exam);
 return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui",color:"#172033",padding:24}}><div style={{maxWidth:720,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><b>ADAPTIVE SYLLABUS</b><h1 style={{margin:"6px 0"}}>My Profile</h1></div><button style={btn} onClick={logout}>Logout</button></div>{message&&<div style={{padding:12,borderRadius:9,background:"#f0f7ff",margin:"16px 0"}}>{message}</div>}
 <section style={{background:"white",border:"1px solid #dfe5ed",borderRadius:14,padding:20,marginTop:18}}><h2>Personal details</h2><p style={{fontSize:13,color:"#667085"}}>Correct your details anytime. User ID and role are fixed.</p><label style={{fontSize:13}}>User ID</label><input style={{...input,margin:"6px 0 14px",background:"#f3f4f6"}} value={profile.user_id||""} disabled/><label>Name</label><input style={{...input,margin:"6px 0 14px"}} value={name} onChange={e=>setName(e.target.value)}/><label>Date of birth</label><input type="date" style={{...input,margin:"6px 0 14px"}} value={dob} onChange={e=>setDob(e.target.value)}/><div style={{fontSize:13,color:"#667085",marginBottom:14}}>Role: <b>{profile.role}</b></div><button disabled={busy} onClick={save} style={{...primary,opacity:busy?.7:1}}>{busy?"Saving…":"Save profile"}</button></section>
 <section style={{background:"white",border:"1px solid #dfe5ed",borderRadius:14,padding:20,marginTop:14}}><h2>My exams</h2><p style={{fontSize:13,color:"#667085"}}>Add multiple exams. Only the active exam controls Practice, Syllabus and Analytics.</p>{exams.map(x=><div key={x.exam} style={{display:"flex",alignItems:"center",gap:8,padding:"12px 0",borderBottom:"1px solid #edf0f4"}}><div style={{flex:1}}><b>{EXAM_PROFILES[x.exam]?.shortName||x.exam}</b><div style={{fontSize:12,color:"#667085"}}>{EXAM_PROFILES[x.exam]?.name||x.exam}</div></div>{profile.exam===x.exam?<span style={{fontSize:12,fontWeight:700}}>ACTIVE</span>:<button style={btn} disabled={busy} onClick={()=>switchExam(x.exam)}>Switch</button>}<button style={btn} disabled={busy||exams.length<=1} onClick={()=>removeExam(x.exam)}>Remove</button></div>)}<h3>Add another exam</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{Object.values(EXAM_PROFILES).filter(e=>e.id!=="custom"&&!ids.includes(e.id)).map(e=><button key={e.id} style={btn} disabled={busy} onClick={()=>addExam(e.id)}>+ {e.shortName}</button>)}</div></section><button style={{...btn,marginTop:14}} onClick={()=>router.push("/")}>← Dashboard</button></div></main>;
}
