"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {getCloudProfile,supabase} from "../lib/supabase";
const card={background:"#fff",border:"1px solid #dfe5ed",borderRadius:14,padding:18,marginBottom:14};
const btn={padding:"9px 13px",borderRadius:9,border:"1px solid #ccd4df",background:"#fff",cursor:"pointer",fontWeight:600};
const primary={...btn,background:"#172033",color:"#fff",borderColor:"#172033"};
const examNames={ras:"RAS",upsc:"UPSC CSE",ssc_cgl:"SSC CGL",banking:"Banking",police:"Police SI",neet:"NEET UG"};
function formatLeft(sec){sec=Math.max(0,Math.floor(sec));return `${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`;}
export default function LiveTest(){
 const router=useRouter();const[profile,setProfile]=useState(null),[live,setLive]=useState([]),[results,setResults]=useState([]),[selected,setSelected]=useState(null),[questions,setQuestions]=useState([]),[answers,setAnswers]=useState({}),[startedAt,setStartedAt]=useState(null),[left,setLeft]=useState(0),[mode,setMode]=useState("list"),[result,setResult]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||"";}
 async function load(){try{const p=await getCloudProfile();if(!p){router.replace("/");return;}setProfile(p);const t=await token();const res=await fetch("/api/live-test",{headers:{Authorization:`Bearer ${t}`}});const body=await res.json();if(!res.ok)throw new Error(body.error||"Unable to load live tests.");setLive(body.live||[]);setResults(body.results||[]);}catch(e){setMessage(e?.message||"Unable to load live tests.");}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function openTest(t){setMessage("");try{const tok=await token();const res=await fetch(`/api/live-test/${t.id}`,{headers:{Authorization:`Bearer ${tok}`}});const body=await res.json();if(!res.ok)throw new Error(body.error||"Unable to open test.");setSelected(body.test);if(body.mode==="result"){setResult({attempt:body.attempt,rank:body.rank});setMode("result");return;}if(body.mode!=="live"){setMessage(`This test is available from ${new Date(body.test.start_at).toLocaleString()} until ${new Date(body.test.end_at).toLocaleString()}.`);return;}setQuestions(body.questions||[]);setAnswers({});const saved=localStorage.getItem(`live-answer-${t.id}`);if(saved)try{setAnswers(JSON.parse(saved))}catch{}const sa=localStorage.getItem(`live-start-${t.id}`)||new Date().toISOString();localStorage.setItem(`live-start-${t.id}`,sa);setStartedAt(sa);setLeft(Math.min(Number(body.test.duration_sec||1800),Math.max(0,Math.floor((new Date(body.test.end_at)-new Date(sa))/1000))));setMode("test");}catch(e){setMessage(e?.message||"Unable to open test.");}}
 useEffect(()=>{if(mode!=="test"||!selected)return;const tick=()=>{const elapsed=Math.floor((Date.now()-new Date(startedAt).getTime())/1000);const remain=Math.min(Number(selected.duration_sec||1800)-elapsed,Math.floor((new Date(selected.end_at).getTime()-Date.now())/1000));setLeft(Math.max(0,remain));if(remain<=0)submit(true)};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[mode,selected,startedAt]);
 function choose(qid,val){setAnswers(a=>{const n={...a,[qid]:val};if(selected)localStorage.setItem(`live-answer-${selected.id}`,JSON.stringify(n));return n})}
 async function submit(auto=false){if(busy||!selected)return;if(!auto&&!window.confirm("Submit your test now? You cannot change answers after submission."))return;setBusy(true);try{const tok=await token();const res=await fetch(`/api/live-test/${selected.id}`,{method:"POST",headers:{Authorization:`Bearer ${tok}`,"Content-Type":"application/json"},body:JSON.stringify({answers,startedAt})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Unable to submit.");setResult({attempt:body.attempt,rank:body.rank});localStorage.removeItem(`live-answer-${selected.id}`);localStorage.removeItem(`live-start-${selected.id}`);setMode("result");}catch(e){setMessage(e?.message||"Submission failed.");}finally{setBusy(false)}}
 const answered=useMemo(()=>Object.values(answers).filter(v=>v!==null&&v!==undefined&&v!=="").length,[answers]);
 if(loading)return <main style={{padding:24,fontFamily:"system-ui"}}>Loading live tests…</main>;
 if(mode==="test"&&selected)return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui,-apple-system,sans-serif",color:"#172033"}}><div style={{maxWidth:900,margin:"0 auto",padding:18}}><div style={{...card,position:"sticky",top:8,zIndex:2}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><b>{selected.title}</b><div style={{fontSize:12,color:"#667085"}}>{examNames[selected.exam]||selected.exam} • {answered}/{questions.length} answered</div></div><strong style={{fontSize:22}}>{formatLeft(left)}</strong></div></div>{message&&<div style={card}>{message}</div>}{questions.map((q,i)=><section key={q.id} style={card}><div style={{fontSize:13,color:"#667085"}}>Question {i+1} of {questions.length}</div><h3 style={{marginBottom:6}}>{q.question}</h3>{q.question_hi&&<div style={{fontWeight:600,marginBottom:10}}>{q.question_hi}</div>}<div>{(q.options||[]).map((op,j)=>{const hi=q.options_hi?.[j]||"";return <label key={j} style={{display:"block",padding:12,border:"1px solid #dfe5ed",borderRadius:9,margin:"7px 0",cursor:"pointer",background:String(answers[q.id])===String(j)?"#eef2f7":"#fff"}}><input type="radio" name={q.id} checked={String(answers[q.id])===String(j)} onChange={()=>choose(q.id,j)} style={{marginRight:9}}/>{String.fromCharCode(65+j)}. {op}{hi&&<> / {hi}</>}</label>})}</div></section>)}<button style={{...primary,width:"100%",padding:14}} disabled={busy}>{busy?"Submitting…":"Submit Test"}</button></div></main>;
 if(mode==="result"&&selected&&result)return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui,-apple-system,sans-serif",color:"#172033"}}><div style={{maxWidth:650,margin:"0 auto",padding:24}}><section style={{...card,textAlign:"center",padding:30}}><div style={{fontSize:13,color:"#667085"}}>TEST COMPLETED</div><h1>{selected.title}</h1><div style={{fontSize:48,fontWeight:800}}>{result.attempt.score}</div><p>Score</p><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,margin:"20px 0"}}><div><b>{result.attempt.correct}</b><br/><small>Correct</small></div><div><b>{result.attempt.wrong}</b><br/><small>Wrong</small></div><div><b>{result.attempt.unanswered}</b><br/><small>Unanswered</small></div></div><div style={{fontSize:22,fontWeight:700}}>Rank #{result.rank}</div><p style={{color:"#667085"}}>The live period has ended or you have submitted. Your result is now available.</p><button style={primary} onClick={()=>{setMode("list");setSelected(null);setResult(null);load()}}>Back to Live Tests</button></section></div></main>;
 return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui,-apple-system,sans-serif",color:"#172033"}}><div style={{maxWidth:1000,margin:"0 auto",padding:24}}><a href="/">← Dashboard</a><h1>Live Tests / लाइव टेस्ट</h1><p style={{color:"#667085"}}>Tests created by the admin for a selected syllabus area. Enter during the live period; results appear after submission and ranking is calculated from submitted attempts.</p>{message&&<div style={card}>{message}</div>}<section style={card}><h2>🔴 Live now</h2>{live.length?live.map(t=><div key={t.id} style={{borderTop:"1px solid #edf0f4",padding:"14px 0",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><b>{t.title}</b><div style={{fontSize:13,color:"#667085"}}>{examNames[t.exam]||t.exam} • Ends {new Date(t.end_at).toLocaleString()}</div>{t.attempt?.submitted_at&&<small>Already submitted</small>}</div>{t.attempt?.submitted_at?<span>Submitted</span>:<button style={primary} onClick={()=>openTest(t)}>Enter Test →</button>}</div>):<p>No live test at this moment.</p>}</section><section style={card}><h2>🏆 Recent Results</h2>{results.length?results.map(t=><div key={t.id} style={{borderTop:"1px solid #edf0f4",padding:"14px 0",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><b>{t.title}</b><div style={{fontSize:13,color:"#667085"}}>{examNames[t.exam]||t.exam} • {new Date(t.end_at).toLocaleString()}</div></div><div style={{textAlign:"right"}}><b>{t.attempt.score}</b><br/><small>Result</small></div></div>):<p>No recent results yet.</p>}</section></div></main>;
}
