"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {getCloudProfile,supabase} from "../lib/supabase";

const card={background:"#fff",border:"1px solid #dfe5ed",borderRadius:16,padding:18,marginBottom:14,boxShadow:"0 2px 8px rgba(16,24,40,.03)"};
const btn={padding:"10px 14px",borderRadius:10,border:"1px solid #ccd4df",background:"#fff",cursor:"pointer",fontWeight:700};
const primary={...btn,background:"#172033",color:"#fff",borderColor:"#172033"};
const examNames={ras:"RAS",upsc:"UPSC CSE",ssc_cgl:"SSC CGL",banking:"Banking",police:"Police SI",neet:"NEET UG"};
function formatLeft(sec){sec=Math.max(0,Math.floor(sec));return `${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`;}
function formatDate(v){return new Date(v).toLocaleString([], {dateStyle:"medium",timeStyle:"short"});}
function countdown(v){const s=Math.max(0,Math.floor((new Date(v).getTime()-Date.now())/1000));const d=Math.floor(s/86400),h=Math.floor((s%86400)/3600),m=Math.floor((s%3600)/60),sec=s%60;return d?`${d}d ${h}h ${m}m`:h?`${h}h ${m}m`:m?`${m}m ${sec}s`:`${sec}s`;}

export default function LiveTest(){
 const router=useRouter();
 const[profile,setProfile]=useState(null),[live,setLive]=useState([]),[upcoming,setUpcoming]=useState([]),[results,setResults]=useState([]),[selected,setSelected]=useState(null),[questions,setQuestions]=useState([]),[answers,setAnswers]=useState({}),[startedAt,setStartedAt]=useState(null),[left,setLeft]=useState(0),[mode,setMode]=useState("list"),[result,setResult]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[clock,setClock]=useState(Date.now()),[current,setCurrent]=useState(0);
 async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||"";}
 async function load(){try{const p=await getCloudProfile();if(!p){router.replace("/");return;}setProfile(p);const t=await token();const res=await fetch("/api/live-test",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});const body=await res.json();if(!res.ok)throw new Error(body.error||"Unable to load live tests.");setLive(body.live||[]);setUpcoming(body.upcoming||[]);setResults(body.results||[]);}catch(e){setMessage(e?.message||"Unable to load live tests.");}finally{setLoading(false)}}
 useEffect(()=>{load();const id=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(id)},[]);
 async function openTest(t){setMessage("");try{const tok=await token();const res=await fetch(`/api/live-test/${t.id}`,{headers:{Authorization:`Bearer ${tok}`},cache:"no-store"});const body=await res.json();if(!res.ok)throw new Error(body.error||"Unable to open test.");setSelected(body.test);if(body.mode==="result"){setResult({attempt:body.attempt,rank:body.rank});setMode("result");return;}if(body.mode!=="live"){setMessage(`This test is available from ${formatDate(body.test.start_at)} until ${formatDate(body.test.end_at)}.`);return;}const qs=body.questions||[];setQuestions(qs);const saved=localStorage.getItem(`live-answer-${t.id}`);let savedAnswers={};if(saved)try{savedAnswers=JSON.parse(saved)||{}}catch{}setAnswers(savedAnswers);const sa=localStorage.getItem(`live-start-${t.id}`)||new Date().toISOString();localStorage.setItem(`live-start-${t.id}`,sa);setStartedAt(sa);setCurrent(0);setLeft(Math.min(Number(body.test.duration_sec||1800),Math.max(0,Math.floor((new Date(body.test.end_at)-new Date(sa))/1000))));setMode("test");}catch(e){setMessage(e?.message||"Unable to open test.");}}
 useEffect(()=>{if(mode!=="test"||!selected||!startedAt)return;const tick=()=>{const elapsed=Math.floor((Date.now()-new Date(startedAt).getTime())/1000);const remain=Math.min(Number(selected.duration_sec||1800)-elapsed,Math.floor((new Date(selected.end_at).getTime()-Date.now())/1000));setLeft(Math.max(0,remain));if(remain<=0)submit(true)};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[mode,selected,startedAt]);
 function choose(qid,val){setAnswers(a=>{const n={...a,[qid]:val};if(selected)localStorage.setItem(`live-answer-${selected.id}`,JSON.stringify(n));return n})}
 async function submit(auto=false){if(busy||!selected)return;if(!auto&&!window.confirm("Submit your test now? You cannot change answers after submission."))return;setBusy(true);try{const tok=await token();const res=await fetch(`/api/live-test/${selected.id}`,{method:"POST",headers:{Authorization:`Bearer ${tok}`,"Content-Type":"application/json"},body:JSON.stringify({answers,startedAt})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Unable to submit.");setResult({attempt:body.attempt,rank:body.rank});localStorage.removeItem(`live-answer-${selected.id}`);localStorage.removeItem(`live-start-${selected.id}`);setMode("result");}catch(e){setMessage(e?.message||"Submission failed.");}finally{setBusy(false)}}
 const answered=useMemo(()=>Object.values(answers).filter(v=>v!==null&&v!==undefined&&v!=="").length,[answers]);
 const progress=questions.length?Math.round(answered/questions.length*100):0;
 const scrollToQuestion=i=>{setCurrent(i);document.getElementById(`live-q-${i}`)?.scrollIntoView({behavior:"smooth",block:"start"});};
 if(loading)return <main style={{padding:24,fontFamily:"system-ui"}}>Loading live tests…</main>;
 if(mode==="test"&&selected)return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui,-apple-system,sans-serif",color:"#172033"}}><div style={{maxWidth:980,margin:"0 auto",padding:18}}>
   <div style={{...card,position:"sticky",top:8,zIndex:5,padding:14}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,flexWrap:"wrap"}}><div style={{minWidth:220}}><b style={{fontSize:18}}>{selected.title}</b><div style={{fontSize:12,color:"#667085",marginTop:3}}>{examNames[selected.exam]||selected.exam} • {answered}/{questions.length} answered • {progress}% complete</div><div style={{height:7,background:"#edf0f4",borderRadius:99,marginTop:8,overflow:"hidden"}}><div style={{width:`${progress}%`,height:"100%",background:"#172033",borderRadius:99}}/></div></div><div style={{textAlign:"center",minWidth:90}}><div style={{fontSize:11,color:"#667085"}}>TIME LEFT</div><strong style={{fontSize:25}}>{formatLeft(left)}</strong></div><button style={primary} disabled={busy} onClick={()=>submit(false)}>{busy?"Submitting…":"Submit Test"}</button></div></div>
   <div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 190px",gap:14,alignItems:"start"}}><div>{message&&<div style={card}>{message}</div>}{questions.map((q,i)=><section id={`live-q-${i}`} key={q.id} style={card}><div style={{fontSize:13,color:"#667085",display:"flex",justifyContent:"space-between"}}><span>Question {i+1} of {questions.length}</span><span>{answers[q.id]!==undefined?"Answered":"Not answered"}</span></div><h3 style={{margin:"10px 0 7px",lineHeight:1.5}}>{q.question}</h3>{q.question_hi&&<div style={{fontWeight:600,marginBottom:10,lineHeight:1.5}}>{q.question_hi}</div>}<div>{(q.options||[]).map((op,j)=>{const hi=q.options_hi?.[j]||"";const checked=String(answers[q.id])===String(j);return <label key={j} style={{display:"block",padding:12,border:`1px solid ${checked?"#172033":"#dfe5ed"}`,borderRadius:10,margin:"7px 0",cursor:"pointer",background:checked?"#f0f2f5":"#fff"}}><input type="radio" name={q.id} checked={checked} onChange={()=>choose(q.id,j)} style={{marginRight:9}}/>{String.fromCharCode(65+j)}. {op}{hi&&<> / {hi}</>}</label>})}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:12,gap:8}}><button style={btn} disabled={i===0} onClick={()=>scrollToQuestion(i-1)}>← Previous</button><button style={btn} disabled={i===questions.length-1} onClick={()=>scrollToQuestion(i+1)}>Next →</button></div></section>)}</div>
   <aside style={{...card,position:"sticky",top:118}}><b>Question Palette</b><div style={{fontSize:12,color:"#667085",margin:"5px 0 12px"}}>{answered} answered / {questions.length}</div><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:6}}>{questions.map((q,i)=><button key={q.id} onClick={()=>scrollToQuestion(i)} aria-label={`Question ${i+1}`} style={{padding:"7px 2px",borderRadius:7,border:i===current?"2px solid #172033":"1px solid #ccd4df",background:answers[q.id]!==undefined?"#172033":"#fff",color:answers[q.id]!==undefined?"#fff":"#172033",fontWeight:700,cursor:"pointer"}}>{i+1}</button>)}</div><div style={{fontSize:11,color:"#667085",marginTop:12}}>■ Answered &nbsp; □ Unanswered</div></aside></div>
 </div></main>;
 if(mode==="result"&&selected&&result)return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui,-apple-system,sans-serif",color:"#172033"}}><div style={{maxWidth:720,margin:"0 auto",padding:24}}><section style={{...card,textAlign:"center",padding:30}}><div style={{fontSize:13,color:"#667085",fontWeight:700}}>TEST COMPLETED</div><h1 style={{marginBottom:4}}>{selected.title}</h1><div style={{color:"#667085"}}>{examNames[selected.exam]||selected.exam}</div><div style={{fontSize:52,fontWeight:800,marginTop:16}}>{result.attempt.score}</div><div style={{color:"#667085"}}>Final Score</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,margin:"24px 0",paddingTop:18,borderTop:"1px solid #edf0f4"}}><div><b>{result.attempt.correct}</b><br/><small>Correct</small></div><div><b>{result.attempt.wrong}</b><br/><small>Wrong</small></div><div><b>{result.attempt.unanswered}</b><br/><small>Unanswered</small></div><div><b>{result.attempt.total}</b><br/><small>Total</small></div></div><div style={{fontSize:26,fontWeight:800}}>🏆 Rank #{result.rank}</div><p style={{color:"#667085"}}>Your result is recorded. Ranking is calculated from submitted attempts.</p><div style={{display:"flex",justifyContent:"center",gap:8,flexWrap:"wrap"}}><button style={primary} onClick={()=>{setMode("list");setSelected(null);setResult(null);load()}}>Back to Live Tests</button></div></section></div></main>;
 const TestRow=({t,kind})=><div key={t.id} style={{borderTop:"1px solid #edf0f4",padding:"16px 0",display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",flexWrap:"wrap"}}><div style={{flex:"1 1 280px"}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><b>{t.title}</b>{kind==="live"&&<span style={{fontSize:11,fontWeight:800,padding:"3px 7px",borderRadius:99,background:"#172033",color:"#fff"}}>LIVE</span>}</div><div style={{fontSize:13,color:"#667085",marginTop:4}}>{examNames[t.exam]||t.exam} • {t.description||"No description"}</div>{kind==="live"?<small>Ends {formatDate(t.end_at)}</small>:<small>Starts {formatDate(t.start_at)} • {clock?`Starts in ${countdown(t.start_at)}`:""}</small>}</div>{kind==="live"?(t.attempt?.submitted_at?<span style={{fontWeight:700}}>✓ Submitted</span>:<button style={primary} onClick={()=>openTest(t)}>Enter Test →</button>):<span style={{color:"#667085",fontWeight:700}}>Scheduled</span>}</div>;
 return <main style={{minHeight:"100vh",background:"#f6f8fb",fontFamily:"system-ui,-apple-system,sans-serif",color:"#172033"}}><div style={{maxWidth:1000,margin:"0 auto",padding:24}}><a href="/">← Dashboard</a><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:15,margin:"18px 0",flexWrap:"wrap"}}><div><div style={{fontSize:13,fontWeight:800,color:"#667085"}}>EXAM ARENA</div><h1 style={{margin:"5px 0"}}>Live Tests / लाइव टेस्ट</h1><p style={{color:"#667085",margin:0}}>Timed tests created from the admin-selected syllabus. Enter during the live window; submit before time expires.</p></div><button style={btn} onClick={load}>↻ Refresh</button></div>{message&&<div style={card}>{message}</div>}
   <section style={card}><h2 style={{marginTop:0}}>🔴 Live Now</h2>{live.length?live.map(t=><TestRow key={t.id} t={t} kind="live"/>):<div style={{padding:"12px 0",color:"#667085"}}>No test is live right now.</div>}</section>
   <section style={card}><h2 style={{marginTop:0}}>🕒 Upcoming Tests</h2>{upcoming.length?upcoming.map(t=><TestRow key={t.id} t={t} kind="upcoming"/>):<div style={{padding:"12px 0",color:"#667085"}}>No upcoming tests.</div>}</section>
   <section style={card}><h2 style={{marginTop:0}}>🏆 Recent Results</h2>{results.length?results.map(t=><div key={t.id} style={{borderTop:"1px solid #edf0f4",padding:"14px 0",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><b>{t.title}</b><div style={{fontSize:13,color:"#667085"}}>{examNames[t.exam]||t.exam} • Ended {formatDate(t.end_at)}</div></div><div style={{textAlign:"right"}}><b style={{fontSize:18}}>{t.attempt.score}</b><br/><small>{t.attempt.correct}/{t.attempt.total} correct</small></div></div>):<div style={{padding:"12px 0",color:"#667085"}}>No recent results yet.</div>}</section>
 </div></main>;
}
