"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {getCloudProfile,supabase} from "../../lib/supabase";
const exams={ras:"RAS",upsc:"UPSC CSE",ssc_cgl:"SSC CGL",banking:"Banking",police:"Police SI",neet:"NEET UG"};
const card={background:"#fff",border:"1px solid #dfe5ed",borderRadius:14,padding:18,marginBottom:16};
const btn={border:"1px solid #cfd7e3",borderRadius:9,padding:"9px 13px",background:"#fff",cursor:"pointer"};
const primary={...btn,background:"#172033",color:"#fff",borderColor:"#172033"};
function date(v){return new Date(v).toLocaleString([], {dateStyle:"medium",timeStyle:"short"});}
export default function AdminLiveTests(){
 const router=useRouter();const[tests,setTests]=useState([]),[selected,setSelected]=useState(null),[details,setDetails]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||"";}
 async function load(){setLoading(true);try{const p=await getCloudProfile();if(!p||p.role!=="admin"){router.replace("/");return;}const r=await fetch("/api/admin/live-tests",{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setTests(b.tests||[]);}catch(e){setMessage(e?.message||"Unable to load test history.");}finally{setLoading(false);}}
 useEffect(()=>{load()},[]);
 async function view(t){setSelected(t);setDetails([]);try{const r=await fetch(`/api/admin/live-tests?testId=${t.id}`,{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setSelected(b.test);setDetails(b.details||[]);}catch(e){setMessage(e?.message||"Unable to load participant analysis.");}}
 if(loading)return <main style={{padding:30,fontFamily:"system-ui"}}>Loading live-test history…</main>;
 const now=Date.now();
 return <main style={{minHeight:"100vh",background:"#f6f8fb",color:"#172033",fontFamily:"system-ui"}}><div style={{maxWidth:1150,margin:"0 auto",padding:24}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><button style={btn} onClick={()=>router.push("/admin")}>← Admin</button><h1>Live Test History & Analysis</h1><p style={{color:"#58657a"}}>Every organized test remains recorded, with participant performance and question-level analysis.</p></div><button style={btn} onClick={load}>↻ Refresh</button></div>
  {message&&<div style={card}>{message}</div>}
  <section style={card}><h2>Past & Scheduled Tests</h2>{tests.length?tests.map(t=>{const ended=new Date(t.end_at).getTime()<now;const live=new Date(t.start_at).getTime()<=now&&!ended;return <div key={t.id} style={{padding:"15px 0",borderTop:"1px solid #edf0f4",display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap"}}><div style={{flex:"1 1 400px"}}><b>{t.title}</b><div style={{fontSize:13,color:"#667085",marginTop:4}}>{exams[t.exam]||t.exam} • {t.questionCount??"—"} questions • {t.description||"No description"}</div><small>{date(t.start_at)} → {date(t.end_at)}</small></div><div style={{minWidth:210}}><b>{live?"🔴 LIVE":ended?"✓ COMPLETED":"🕒 UPCOMING"}</b><div style={{fontSize:13,marginTop:4}}>{t.participantCount} submitted • {t.attemptCount} attempts</div><div style={{fontSize:13}}>Avg {t.averageScore} • Best {t.highestScore}</div><button style={{...primary,marginTop:8}} onClick={()=>view(t)}>View Analysis →</button></div></div>}) : <p>No live tests have been recorded yet.</p>}</section>
  {selected&&<section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2>{selected.title}</h2><p>{exams[selected.exam]||selected.exam} • {selected.questionCount||0} questions</p></div><button style={btn} onClick={()=>setSelected(null)}>Close</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,margin:"15px 0"}}>{[["Participants",selected.participantCount],["Average",selected.averageScore],["Highest",selected.highestScore],["Questions",selected.questionCount||0]].map(x=><div key={x[0]} style={{...card,margin:0}}><small>{x[0]}</small><div style={{fontSize:24,fontWeight:800}}>{x[1]}</div></div>)}</div><h3>Participant performance</h3>{selected.participants?.length?selected.participants.map((p,i)=><div key={p.id} style={{padding:12,borderTop:"1px solid #edf0f4",display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><b>#{i+1} {p.student?.name||"Student"}</b><br/><small>{p.student?.user_id||""}</small></div><div><b>{p.score}</b> score • {p.correct} correct • {p.wrong} wrong • {p.unanswered} unanswered</div></div>):<p>No participant has submitted this test yet.</p>}{details.length>0&&<div style={{marginTop:20}}><h3>Question-level analysis — selected top participant</h3>{details.map(d=><div key={d.number} style={{padding:12,borderTop:"1px solid #edf0f4"}}><b>Q{d.number} {d.correct?"✓":"✗"}</b> — {d.subject||d.topic||d.concept||"Unmapped"}<div style={{marginTop:4}}>{d.question}</div><small>Your answer: {d.selected===null?"Not answered":String.fromCharCode(65+Number(d.selected))} • Correct: {d.correctOption||"—"}</small>{d.explanation&&<p style={{color:"#58657a"}}>{d.explanation}</p>}</div>)}</div>}</section>}
 </div></main>;
}
