"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {getCloudProfile,supabase} from "../../lib/supabase";
const exams={ras:"RAS",upsc:"UPSC CSE",ssc_cgl:"SSC CGL",banking:"Banking",police:"Police SI",neet:"NEET UG"};
const card={background:"#fff",border:"1px solid #dfe5ed",borderRadius:14,padding:18,marginBottom:16};
const btn={border:"1px solid #cfd7e3",borderRadius:9,padding:"9px 13px",background:"#fff",cursor:"pointer"};
const primary={...btn,background:"#172033",color:"#fff",borderColor:"#172033"};
function date(v){return new Date(v).toLocaleString([], {dateStyle:"medium",timeStyle:"short"});}
export default function AdminLiveTests(){
 const router=useRouter();const[tests,setTests]=useState([]),[selected,setSelected]=useState(null),[weak,setWeak]=useState([]),[questions,setQuestions]=useState([]),[participantDetails,setParticipantDetails]=useState([]),[student,setStudent]=useState(null),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 async function token(){const{data}=await supabase.auth.getSession();return data.session?.access_token||"";}
 async function load(){setLoading(true);try{const p=await getCloudProfile();if(!p||p.role!=="admin"){router.replace("/");return;}const r=await fetch("/api/admin/live-tests",{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setTests(b.tests||[]);}catch(e){setMessage(e?.message||"Unable to load test history.");}finally{setLoading(false);}}
 useEffect(()=>{load()},[]);
 async function view(t){setSelected(t);setStudent(null);setWeak([]);setQuestions([]);setParticipantDetails([]);try{const r=await fetch(`/api/admin/live-tests?testId=${t.id}`,{headers:{Authorization:`Bearer ${await token()}`},cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setSelected(b.test);setWeak(b.weakTopics||[]);setQuestions(b.questionAnalysis||[]);setParticipantDetails(b.participantDetails||[]);}catch(e){setMessage(e?.message||"Unable to load analysis.");}}
 if(loading)return <main style={{padding:30,fontFamily:"system-ui"}}>Loading live-test analysis…</main>;
 const now=Date.now();
 return <main style={{minHeight:"100vh",background:"#f6f8fb",color:"#172033",fontFamily:"system-ui"}}><div style={{maxWidth:1180,margin:"0 auto",padding:24}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><button style={btn} onClick={()=>router.push("/admin")}>← Admin</button><h1 style={{marginBottom:4}}>Live Test Analysis</h1><p style={{color:"#58657a",marginTop:0}}>Cohort performance, weak topics and individual participant drill-down.</p></div><button style={btn} onClick={load}>↻ Refresh</button></div>
  {message&&<div style={card}>{message}</div>}
  <section style={card}><h2>Test history</h2>{tests.length?tests.map(t=>{const ended=new Date(t.end_at).getTime()<now,live=new Date(t.start_at).getTime()<=now&&!ended;return <div key={t.id} style={{padding:"15px 0",borderTop:"1px solid #edf0f4",display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap"}}><div style={{flex:"1 1 420px"}}><b>{t.title}</b><div style={{fontSize:13,color:"#667085",marginTop:4}}>{exams[t.exam]||t.exam} • {t.description||"No description"}</div><small>{date(t.start_at)} → {date(t.end_at)}</small></div><div style={{minWidth:230}}><b>{live?"🔴 LIVE":ended?"✓ COMPLETED":"🕒 UPCOMING"}</b><div style={{fontSize:13,marginTop:4}}>{t.participantCount} submitted • {t.attemptCount} attempts • Avg {t.averageScore}</div><button style={{...primary,marginTop:8}} onClick={()=>view(t)}>Analyze →</button></div></div>}) : <p>No live tests have been recorded yet.</p>}</section>
  {selected&&<section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2 style={{marginBottom:4}}>{selected.title}</h2><p style={{marginTop:0,color:"#667085"}}>{exams[selected.exam]||selected.exam} • {selected.questionCount||0} questions</p></div><button style={btn} onClick={()=>setSelected(null)}>Close</button></div>
   <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10,margin:"15px 0"}}>{[["Participants",selected.participantCount],["Average",selected.averageScore],["Highest",selected.highestScore],["Questions",selected.questionCount||0]].map(x=><div key={x[0]} style={{...card,margin:0}}><small>{x[0]}</small><div style={{fontSize:24,fontWeight:800}}>{x[1]}</div></div>)}</div>
   <h3>🔴 Weak topics & concepts</h3><p style={{fontSize:13,color:"#667085"}}>Lowest accuracy first; student count shows how widespread the weakness is.</p>{weak.length?weak.slice(0,12).map((w,i)=><div key={w.node_id||i} style={{padding:13,borderTop:"1px solid #edf0f4",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><b>{w.label}</b><div style={{fontSize:12,color:"#667085"}}>{w.questions} questions • {w.attempts} responses • {w.students} students affected</div></div><b style={{fontSize:18}}>{w.accuracy}%</b></div>):<p>No submitted answers yet.</p>}
   <h3 style={{marginTop:26}}>Question performance</h3>{questions.slice().sort((a,b)=>a.accuracy-b.accuracy).slice(0,15).map(q=><div key={q.id} style={{padding:12,borderTop:"1px solid #edf0f4"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><b>Q{q.number} • {q.label}</b><b>{q.accuracy}%</b></div><small>{q.correct} correct • {q.wrong} wrong • {q.unanswered} unanswered</small><div style={{fontSize:13,marginTop:5}}>{q.question}</div></div>)}
   <h3 style={{marginTop:26}}>Participant performance</h3>{selected.participants?.length?selected.participants.map((p,i)=><div key={p.id} style={{padding:13,borderTop:"1px solid #edf0f4",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><b>#{i+1} {p.student?.name||"Student"}</b><div style={{fontSize:12,color:"#667085"}}>{p.student?.user_id||""} • {p.correct} correct • {p.wrong} wrong • {p.unanswered} unanswered • {p.accuracy}% accuracy</div>{p.weakAreas?.length>0&&<div style={{fontSize:12,marginTop:4}}>Weak: {p.weakAreas.map(x=>`${x.label} (${x.accuracy}%)`).join(" • ")}</div>}</div><div style={{display:"flex",alignItems:"center",gap:10}}><b>{p.score}</b><button style={btn} onClick={()=>setStudent(participantDetails.find(x=>x.id===p.id)||null)}>Detailed performance</button></div></div>):<p>No participant has submitted this test yet.</p>}
   {student&&<div style={{...card,marginTop:18,border:"2px solid #dfe5ed"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><h3 style={{marginTop:0}}>{student.name}</h3><small>{student.user_id}</small></div><button style={btn} onClick={()=>setStudent(null)}>Close</button></div><h4>Wrong / unanswered questions</h4>{student.answers.filter(a=>!a.correct).map(a=><div key={a.id} style={{padding:12,borderTop:"1px solid #edf0f4"}}><b>Q{a.number} • {[a.subject,a.topic,a.concept].filter(Boolean).join(" • ")||"Unmapped"}</b><div style={{marginTop:5}}>{a.question}</div><small>{a.selected===null?"Unanswered":`Selected ${String.fromCharCode(65+Number(a.selected))}`} • Correct {a.correctOption||"—"}</small>{a.explanation&&<p style={{color:"#58657a",lineHeight:1.5}}>{a.explanation}</p>}</div>)}</div>}
  </section>
 </div></main>;
}
