import { NextResponse } from "next/server";

function answerMapFromText(text){const map=[];const s=text.match(/(?:answer\s*key|answers|ans\.?\s*key)[:\s\n]+([\s\S]{0,20000})/i);if(!s)return map;const r=/(?:Q(?:uestion)?\.?\s*)?(\d{1,3})?\s*[-.:)]?\s*([A-E]|[1-5])/gi;let m;while((m=r.exec(s[1])))map[m[1]?Number(m[1]):map.length+1]=m[2].toUpperCase();return map}
function markerRegex(){return /(?:^|\s)[(\[]?(A|B|C|D|E|1|2|3|4|5)[).:\]]?\s+/gi}
function makeQuestion(stem,parts,index,answers){const opts=parts.map(x=>x.replace(/^\s*[(\[]?(?:A|B|C|D|E|1|2|3|4|5)[).:\]]?\s*/i,"").trim()).filter(Boolean).slice(0,5);const raw=answers[index+1];let answer=null;if(raw){const u=raw.toUpperCase();answer=/^[A-E]$/.test(u)?u.charCodeAt(0)-65:/^[1-5]$/.test(u)?Number(u)-1:null}const notAttempted=opts.length===5&&/not\s*attempt|question\s*not\s*attempt|unattempt|छोड़|छोड़|अनुत्तरित/i.test(opts[4]);return{id:index+1,text:stem.replace(/^\s*(?:Q(?:uestion)?\.?\s*)?\d{1,3}[.)]?\s*/i,"").trim(),options:opts,answer,answerSource:raw?"pdf-answer-key":null,notAttemptedOption:notAttempted?4:null}}
function fallbackParse(text){const clean=text.replace(/\r/g,"").replace(/[ \t]+/g," ");const answers=answerMapFromText(text);const numbered=[...clean.matchAll(/(?:^|\n|\s)(?:Q(?:uestion)?\.?\s*)?(\d{1,3})[.)]\s+/gi)];let chunks=[];if(numbered.length>=2){for(let i=0;i<numbered.length;i++){const start=numbered[i].index+(numbered[i][0].length-numbered[i][0].trimStart().length);const end=i+1<numbered.length?numbered[i+1].index:clean.length;chunks.push(clean.slice(start,end).trim())}}const build=chunks.map((chunk,i)=>{const markers=[...chunk.matchAll(markerRegex())];if(markers.length<2)return null;const stem=chunk.slice(0,markers[0].index).trim();const parts=markers.map((m,j)=>chunk.slice(m.index,j+1<markers.length?markers[j+1].index:chunk.length));return makeQuestion(stem,parts,i,answers)}).filter(q=>q&&q.text&&q.options.length>=2);if(build.length)return build.slice(0,100);const am=[...clean.matchAll(/(?:^|\n|\s)[(\[]?(?:A|1)[).:\]]?\s+/gi)];const unnumbered=[];for(let i=0;i<am.length;i++){const nextA=i+1<am.length?am[i+1].index:clean.length;const block=clean.slice(i===0?0:am[i].index,nextA).trim();const rel=[...block.matchAll(markerRegex())];if(rel.length>=2){const stem=block.slice(0,rel[0].index).trim();const parts=rel.map((m,j)=>block.slice(m.index,j+1<rel.length?rel[j+1].index:block.length));if(stem&&parts.length>=2)unnumbered.push(makeQuestion(stem,parts,i,answers))}}return unnumbered.filter(q=>q.text&&q.options.length>=2).slice(0,100)}
function parseJson(content){const cleaned=(content||"").replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();const parsed=JSON.parse(cleaned);return Array.isArray(parsed)?parsed:(parsed.questions||parsed.data||[])}
async function aiExtract(apiKey,model,apiUrl,text){if(!apiUrl?.trim())throw Error("Add the AI API link in Settings.");const prompt=`Extract ALL MCQs from this exam text. Questions may be numbered or unnumbered. Options may use letters A-E OR numbers 1-5. A question may have FOUR options or FIVE options. If there are five options and the fifth says "Question not attempted", "Not attempted", "Unattempted", or equivalent Hindi wording, preserve it as option E/5 and set notAttemptedOption to 4. Do not assume every question has five options. Determine question boundaries from option sequence and semantic context. Return ONLY {"questions":[...]}. Each item: id, text, options, answer (0-4 or null), answerSource, notAttemptedOption (4 or null). Preserve wording and never invent answers. Match a later answer key only when clear.\n\nSOURCE:\n${text.slice(0,120000)}`;const r=await fetch(apiUrl.trim(),{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`,"api-subscription-key":apiKey},body:JSON.stringify({model,messages:[{role:"user",content:prompt}],temperature:0})});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||d?.message||`AI extraction failed (${r.status})`);return parseJson(d?.choices?.[0]?.message?.content||"")}
export async function POST(request){try{const{text="",apiKey,model="sarvam-105b",apiUrl="",baseUrl=""}=await request.json();if(!text.trim())return NextResponse.json({error:"Paste question-paper text first."},{status:400});let questions=[];if(apiKey){try{questions=await aiExtract(apiKey,model,apiUrl||baseUrl,text)}catch(aiError){questions=fallbackParse(text);if(!questions.length)throw aiError}}else questions=fallbackParse(text);if(!questions.length)return NextResponse.json({error:"No MCQs detected. Supported: numbered/unnumbered questions, A-E or 1-5 options, and four- or five-option questions."},{status:422});return NextResponse.json({mode:apiKey?"ai":"fallback",questions:questions.slice(0,100)})}catch(e){return NextResponse.json({error:e.message},{status:500})}}
