"use client";
import {useMemo,useState} from "react";
import {EXAM_PROFILES} from "../lib/exams";
import {PREDEFINED_SYLLABUS} from "../lib/predefinedSyllabus";
import {normalizeImportedQuestion,validateImportedQuestion} from "../lib/importSchema";

const css={page:{minHeight:"100vh",background:"#f6f8fb",color:"#172033",fontFamily:"system-ui,-apple-system,sans-serif"},wrap:{maxWidth:1200,margin:"0 auto",padding:24},card:{background:"white",border:"1px solid #dfe5ed",borderRadius:12,padding:18,marginBottom:14},btn:{border:"1px solid #ccd4df",background:"white",borderRadius:8,padding:"9px 13px",cursor:"pointer"},primary:{background:"#172033",color:"white",border:"1px solid #172033",borderRadius:8,padding:"9px 13px",cursor:"pointer"},input:{width:"100%",boxSizing:"border-box",padding:10,border:"1px solid #ccd4df",borderRadius:8},small:{fontSize:12,color:"#667085"},ok:{color:"#027a48",fontSize:13},bad:{color:"#b42318",fontSize:13}};
function parseCSV(text){const lines=text.replace(/\r/g,"").split("\n").filter(x=>x.trim());if(!lines.length)return[];const parse=s=>{const a=[];let c="",q=false;for(let i=0;i<s.length;i++){const ch=s[i];if(ch==='"'){if(q&&s[i+1]==='"'){c+='"';i++}else q=!q}else if(ch===','&&!q){a.push(c.trim());c=""}else c+=ch}a.push(c.trim());return a};const h=parse(lines[0]);return lines.slice(1).map(line=>{const a=parse(line),o={};h.forEach((k,i)=>o[k]=a[i]??"");return o})}
function parseAI(text){const t=text.trim();if(!t)return[];try{const j=JSON.parse(t);const arr=Array.isArray(j)?j:(Array.isArray(j.questions)?j.questions:[]);if(arr.length)return arr.map(normalizeImportedQuestion)}catch{}return parseCSV(t).map(normalizeImportedQuestion)}
export default function QuestionImport(){
 const [exam,setExam]=useState("ras"),[text,setText]=useState(""),[rows,setRows]=useState([]),[message,setMessage]=useState(""),[selected,setSelected]=useState(new Set()),[bank,setBank]=useState([]);
 const nodes=useMemo(()=>PREDEFINED_SYLLABUS.filter(n=>n.exam===exam),[exam]);
 const nodeSet=useMemo(()=>new Set(nodes.filter(n=>n.level==="concept").map(n=>n.nodeId)),[nodes]);
 const checked=rows.map(q=>({q,errors:validateImportedQuestion(q,new Set(nodes.map(n=>`${n.subject}|${n.topic}${n.subtopic?`|${n.subtopic}`:""}`)))}));
 const valid=checked.filter(x=>!x.errors.length&&nodeSet.has(x.q.nodeId));
 function parse(){const incoming=parseAI(text);setRows(incoming);setSelected(new Set(incoming.map((_,i)=>i)));setMessage(`Parsed ${incoming.length} question(s).`)}
 function toggle(i){setSelected(s=>{const n=new Set(s);n.has(i)?n.delete(i):n.add(i);return n})}
 function loadBank(){try{setBank(JSON.parse(localStorage.getItem("adaptive-question-bank")||"[]"))}catch{setBank([])}}
 function importNow(){const chosen=checked.filter((_,i)=>selected.has(i)&&!checked[i].errors.length&&nodeSet.has(checked[i].q.nodeId)).map(x=>x.q);const existing=JSON.parse(localStorage.getItem("adaptive-question-bank")||"[]");const keys=new Set(existing.map(q=>q.id));const fresh=chosen.filter(q=>!keys.has(q.id));const merged=[...existing,...fresh];localStorage.setItem("adaptive-question-bank",JSON.stringify(merged));setBank(merged);setMessage(`Imported ${fresh.length} new question(s); ${chosen.length-fresh.length} duplicate(s) skipped.`)}
 return <main style={css.page}><div style={css.wrap}>
 <header style={{marginBottom:18}}><b>ADAPTIVE SYLLABUS</b><h1 style={{margin:"6px 0"}}>Question Bank Studio</h1><div style={css.small}>AI/PYQ ingestion with validation, concept mapping, duplicate protection and local persistence.</div></header>
 <section style={css.card}><h2>1. Select exam</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{Object.values(EXAM_PROFILES).map(e=><button key={e.id} style={exam===e.id?css.primary:css.btn} onClick={()=>{setExam(e.id);setRows([]);setSelected(new Set())}}>{e.shortName}</button>)}</div></section>
 <section style={css.card}><h2>2. Import questions</h2><p style={css.small}>Accepts JSON array or CSV generated from your external AI workflow.</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste AI/PYQ output here…" style={{...css.input,minHeight:260,fontFamily:"monospace",fontSize:13}}/><div style={{display:"flex",gap:8,marginTop:10}}><button style={css.primary} onClick={parse}>Parse & validate</button><button style={css.btn} onClick={()=>{setText("");setRows([])}}>Clear</button></div>{message&&<p style={message.startsWith("Imported")?css.ok:css.small}>{message}</p>}</section>
 {rows.length>0&&<section style={css.card}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 4px"}}>3. Review</h2><div style={css.small}>{valid.length}/{rows.length} valid • invalid rows cannot be imported</div></div><div style={{display:"flex",gap:8}}><button style={css.btn} onClick={()=>setSelected(new Set(valid.map(x=>checked.indexOf(x))))}>Select valid</button><button style={css.primary} disabled={!selected.size} onClick={importNow}>Import selected</button></div></div><div style={{marginTop:12}}>{checked.map(({q,errors},i)=><div key={q.id+"-"+i} style={{padding:12,borderBottom:"1px solid #edf0f4"}}><label style={{display:"flex",gap:10}}><input type="checkbox" checked={selected.has(i)} onChange={()=>toggle(i)} disabled={!!errors.length}/><span><b>{i+1}. {q.text||"Missing question"}</b><div style={css.small}>{q.nodeId||"no node_id"} • {q.difficulty||"difficulty missing"} • answer {q.answer==null?"missing":String.fromCharCode(65+q.answer)}</div>{errors.length>0&&<div style={{marginTop:6,...css.bad}}>{errors.join(" • ")}</div>}</span></label></div>)}</div></section>}
 <section style={css.card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2 style={{margin:0}}>Question bank</h2><div style={css.small}>Persistent for this browser and ready for later dashboard/data-store wiring.</div></div><button style={css.btn} onClick={loadBank}>Refresh</button></div><div style={{marginTop:10,fontSize:28,fontWeight:700}}>{bank.length}</div><div style={css.small}>questions stored</div></section>
 </div></main>;
}
